=== Eksempler på begrepsbeskrivelser [[Del1-eksempler-på-begrepsbeskrivelser]]

|===
a|*Eksempel på en begrepsbeskrivelse med kun obligatoriske opplysninger*, basert på begrepet https://data.norge.no/concepts/798f7000-6e16-3bb2-9b84-66d37a5523a1[«mødrekvote» &#x29C9;, window="_blank", role="ext-link"], hentet fra Data.norge.no, 2025-11-18:

* *anbefalt term*: «mødrekvote» (bokmål), «mødrekvote» (nynorsk)
* *definisjon*: «den delen av foreldrepengeperioden som er forbeholdt mor» (bokmål)
* *identifikator*: \https://data.nav.no/begrep/BEGREP-975
* *kontaktpunkt*: mailto:begrepskatalogen@nav.no[begrepskatalogen@nav.no]
* *publisert av*: NAV
|===

|===
a|*Eksempel på noen anbefalte opplysninger*, basert på begrepet https://termlex.no/term/174124355709972/nb[«innholdsdefinisjon» &#x29C9;, window="_blank", role="ext-link"], hentet fra Termlex til Standard Norge, 2025-11-18:

* *fagområde*: «terminologi» (bokmål)
* *merknad*: «Innholdsdefinisjoner foretrekkes framfor andre typer definisjoner (3.3.1) fordi de tydelig avdekker kjennetegnene (3.2.1) til et begrep (3.2.7) i et begrepssystem (3.2.28): de bør brukes når det er mulig.» (bokmål)
* *tillatt term*: «intensjonell definisjon» (bokmål)
|===

|===
a|*Eksempel på noen valgfrie opplysninger*, ved å bruke et fiktivt eksempel, begrepet «fiktivt begrep»:

* *datastrukturterm*: aFictiveConcept
* *eksempel*: «eksempelbegrep, testbegrep» (bokmål)
* *frarådd term*: «fiktivt konsept» (bokmål)
* *status*: gyldig
* *verdiområde*: lovlige verdier: eksempelbegrep, testbegrep, tullebegrep
* *versjonsnummer*: 1.1
* *versjonsnote*: «Nå med 'tullebegrep' også som en lovlig verdi» (bokmål)
* *inngår i begrepssamling*: Fiktiv begrepssamling
|===

|===
a|*Eksempel på en generisk relasjon*, basert på https://data.norge.no/specification/termlosen/#kap1.4.1[figur 4 i kap. 1.4.1 i Termlosen &#x29C9;, window="_blank", role="ext-link"], for begrepet «tre»:

* *generaliserer*: «eviggrønt tre» (nynorsk)
* *inndelingskriterium*: «bladfelling» (nynorsk)
|===

|===
a|*Eksempel på en partitiv relasjon*, basert på https://data.norge.no/specification/termlosen/#kap1.4.2[figur 6 i kap. 1.4.2 i Termlosen &#x29C9;, window="_blank", role="ext-link"], for begrepet «rot»:

* *helhetsbegrep*: «tre» (nynorsk)
* *inndelingskriterium*: «anatomi» (nynorsk)
|===

|===
a|*Eksempel på en assosiativ relasjon*, basert på begrepet https://data.norge.no/concepts/8bea51a9-23e9-3177-9900-850d18d33f97[«lovlig opphold» &#x29C9;, window="_blank", role="ext-link"], hentet fra Felles datakatalog, 2025-11-18:

* *relasjonsrolle*: muliggjør
* *til-begrep*: https://data.norge.no/concepts/9b4023a0-99b6-3352-9e4e-cc0944e66f40[«medlem i folketrygden» &#x29C9;, window="_blank", role="ext-link"] 
|===
