=== Krav til RDF-representasjon av Generisk begrepsrelasjon [[Generisk-begrepsrelasjon]]

[cols="30s,70d"]
|===
| _English name_  | _Generic concept relation_
| Anvendelse / _Usage note_  | Klassen brukes til å representere en https://termbasen.standard.no/term/165575612703726/nob[generisk begrepsrelasjon].

_This class is used to represent a https://termbasen.standard.no/term/165575612703726/eng[generic concept relation]._
| URI  |skosno:GenericConceptRelation
| Kravnivå / _Requirement level_  |Valgfri / _Optional_
|===

==== Obligatoriske egenskaper for Generisk begrepsrelasjon [[Generisk-begrepsrelasjon-obligatoriske-egenskaper]]

===== Generisk begrepsrelasjon – har overbegrep (skosno:hasGenericConcept) [[Generisk-begrepsrelasjon-har-overbegrep]]

[cols="30s,70d"]
|===
| _English name_  | _has generic concept_
| URI  |skosno:hasGenericConcept
| Verdiområde / _Range_  |skos:Concept
| Anvendelse / _Usage note_ | Egenskapen brukes til å referere til https://termbasen.standard.no/term/165575654205842/nob[det generiske begrepet] i en generisk begrepsrelasjon.

_This property is used to specify the https://termbasen.standard.no/term/165575654205842/eng[generic concept] in a generic concept relation._
| Multiplisitet / _Multiplicity_  |1..n
| Kravnivå / _Requirement level_  |Obligatorisk / _Mandatory_
| Merknad 1 / _Note 1_ | Enten denne eller egenskapen <<Generisk-begrepsrelasjon-har-underbegrep>> skal brukes, men ikke begge samtidig.

_Either this property or the property <<Generisk-begrepsrelasjon-har-underbegrep>> shall be used, not both at the same time._
| Merknad 2 | Vi har i denne standarden valgt å bruke de norske termene «overbegrep» og «underbegrep» kun i generiske relasjoner, mens NS-ISO 1087 bruker disse i både generiske og partitive relasjoner.
|===

Eksempel i RDF Turtle, for NAVs begrep 974 «foreldrepengeperiode»:
-----
<https://data.norge.no/concepts/4729eca4-f145-4518-8309-3e02a84dfc55> a skos:Concept ; # begrep "foreldrepengeperiode"
   skosno:hasGenericConceptRelation [ a skosno:GenericConceptRelation ; # har generisk relasjon
      skosno:hasGenericConcept <https://data.norge.no/concepts/680b83b6-46f5-30f2-96f7-e36c4e5cf3d1> ; ] ; # som har overbegrep "ytelsesperiode"
     .
-----

===== Generisk begrepsrelasjon – har underbegrep (skosno:hasSpecificConcept) [[Generisk-begrepsrelasjon-har-underbegrep]]

[cols="30s,70d"]
|===
| _English name_  | _has specific concept_
| URI  |skosno:hasSpecificConcept
| Verdiområde / _Range_  |skos:Concept
| Anvendelse / _Usage note_  | Egenskapen brukes til å referere til https://termbasen.standard.no/term/165575654205860/nob[det spesifikke begrepet] i en generisk begrepsrelasjon.

_This property is used to refer to the https://termbasen.standard.no/term/165575654205860/eng[specific concept] in a generic concept relation._
| Multiplisitet / _Multiplicity_  |1..n
| Kravnivå / _Requirement level_  |Obligatorisk / _Mandatory_
| Merknad 1 / _Note 1_ | Enten denne eller egenskapen <<Generisk-begrepsrelasjon-har-overbegrep>> skal brukes, ikke begge samtidig.

_Either this property or the property <<Generisk-begrepsrelasjon-har-overbegrep>> shall be used, not both at the same time._
| Merknad 2 | Vi har i denne standarden valgt å bruke de norske termene «overbegrep» og «underbegrep» kun i generiske relasjoner, mens NS-ISO 1087 bruker disse i både generiske og partitive relasjoner.
|===

Eksempel i RDF Turtle, for NAVs begrep 625 «ytelsesperiode»:
-----
<https://data.norge.no/concepts/680b83b6-46f5-30f2-96f7-e36c4e5cf3d1> a skos:Concept ; # begrep "ytelsesperiode"
   skosno:hasGenericConceptRelation [ a skosno:GenericConceptRelation ; # har generisk relasjon
      skosno:hasSpecificConcept <https://data.norge.no/concepts/4729eca4-f145-4518-8309-3e02a84dfc55> ; ] ; # som har underbegrep "foreldrepengeperiode"
     .
-----

==== Anbefalte egenskaper for Generisk begrepsrelasjon [[Generisk-begrepsrelasjon-anbefalte-egenskaper]]


===== Generisk begrepsrelasjon – inndelingskriterium (dct:description) [[Generisk-begrepsrelasjon-inndelingskriterium]]

[cols="30s,70d"]
|===
| _English name_  | _criterion of subdivision_
| URI  |dct:description
| Verdiområde / _Range_  |rdf:langString
| Anvendelse / _Usage note_  | Egenskapen brukes til å oppgi https://termbasen.standard.no/term/165577770503947/nob[inndelingskriterium] for begrepsrelasjonen. Egenskapen bør gjentas når teksten er på flere språk.

_This property is used to specify the https://termbasen.standard.no/term/165577770503947/eng[criterion of subdivision] for the concept relation. This property should be repeated when the text is in several languages._
| Multiplisitet / _Multiplicity_  |0..n
| Kravnivå / _Requirement level_  |Anbefalt / _Recommended_
|===

Eksempel i RDF Turtle:
-----
<tre> a skos:Concept ; # begrep ‘tre’
   skosno:hasGenericConceptRelation [ a skosno:GenericConceptRelation ; # har generisk relasjon
      skosno:hasSpecificConcept <løvtre> ; # … som har ‘løvtre’ som underbegrep
      dct:description "anatomi"@nb ; ] ; # med inndelingskriterium «anatomi» (bokmål)
  .
-----
