=== Krav til RDF-representasjon av Assosiativ begrepsrelasjon [[Assosiativ-begrepsrelasjon]]

[cols="30s,70d"]
|===
| _English name_  | _Associative concept relation_
| Anvendelse / _Usage note_  | Klassen brukes til å representere en https://termbasen.standard.no/term/165575612703735/nob[assosiativ begrepsrelasjon].

_This class is used to represent an https://termbasen.standard.no/term/165575612703735/eng[associative concept relation]._
| URI  |skosno:AssociativeConceptRelation
| Kravnivå / _Requirement level_  |Valgfri / _Optional_
|===

==== Obligatoriske egenskaper for Assosiativ begrepsrelasjon [[Assosiativ-begrepsrelasjon-obligatoriske-egenskaper]]

===== Assosiativ begrepsrelasjon – har til-begrep (skosno:hasToConcept) [[Assosiativ-begrepsrelasjon-har-til-begrep]]

[cols="30s,70d"]
|===
| _English name_  | _has to-concept_
| URI  |skosno:hasToConcept
| Verdiområde / _Range_  |skos:Concept
| Anvendelse / _Usage note_  | Egenskapen brukes til å referere til et til-begrep i en assosiativ begrepsrelasjon.

_This property is used to refer to a to-concept in an associative concept relation._
| Multiplisitet / _Multiplicity_  |1..n
| Kravnivå / _Requirement level_  |Obligatorisk / _Mandatory_
|===

Eksempel i RDF Turtle, for NAVs begrep 1169 «lovlig opphold»:
-----
<https://data.nav.no/begrep/BEGREP-1169> a skos:Concept ; # begrep 1169
   skosno:isFromConceptIn [ a skosno:AssociativeConceptRelation ; # er fra-begrep i en assosiativ relasjon
      skosno:hasToConcept <https://data.nav.no/begrep/BEGREP-170> ; ] ; # … som har til-begrep
     .
-----

===== Assosiativ begrepsrelasjon – relasjonsrolle (skosno:relationRole) [[Assosiativ-begrepsrelasjon-relasjonsrolle]]

[cols="30s,70d"]
|===
| _English name_  | _relation role_
| URI  |skosno:relationRole
| Verdiområde / Range  |skos:Concept or rdf:langString
| Anvendelse / _Usage note_  | Egenskapen brukes til å oppgi relasjonsrollen begrepet har overfor det andre begrepet i den assosiative relasjonen. Verdien skal oppgis enten som kodet verd valgt fra et kontrollert vokabular, eller som tekst. Når tekst er brukt, bør egenskapen gjentas hvis teksten er i flere språk.

_This property is used to specify the relation role the concept has towards the other concept in the associative relation. The value shall be either a coded value chosen from a controlled vocabulary, or text. When text is used, this property should be repeated if the text is in parallel languages._
| Multiplisitet / _Multiplicity_  |1..1 når skos:Concept brukes, 1..n når rdf:langString brukes

_1..1 when skos:Concept is used, 1..n when rdf:langString is used_
| Kravnivå / _Requirement level_  | Obligatorisk / _Mandatory_
|===

Eksempel i RDF Turtle, for NAVs begrep 1169 «lovlig opphold»:
-----
<https://data.nav.no/begrep/BEGREP-1169> a skos:Concept ; # begrep 1169
   skosno:isFromConceptIn [ a skosno:AssociativeConceptRelation ; # er fra-begrep i en assosiativ relasjon
      skosno:hasToConcept <https://data.nav.no/begrep/BEGREP-170> ;  # … som har til-begrep
      skosno:relationRole <muliggjør> ; ] ; # relasjonsrolle
     .
-----
