=== Krav til RDF-representasjon av Begrep [[Begrep]]

[cols="30s,70d"]
|===
| _English name_ | _Concept_
| Anvendelse / _Usage note_ | Klassen brukes til å representere et https://termbasen.standard.no/term/167505058608413/nb?origin=%2Fsearch-results%3FsearchText%3Dbegrep%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[begrep].

_The class is used to represent a https://termbasen.standard.no/term/167505058608413/nb?origin=%2Fsearch-results%3FsearchText%3Dbegrep%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[concept]._
| URI |skos:Concept
| Kravnivå / _Requirement level_ |Obligatorisk / _Mandatory_
|===

Eksempel i RDF Turtle, for NAVs begrep 975:
-----
<https://data.norge.no/concepts/6bd8baed-c9d7-4dbc-b850-78ceeebdc1d5> a skos:Concept ;
   .
-----

==== Obligatoriske egenskaper for _Begrep_ [[Begrep-obligatoriske-egenskaper]]

===== Begrep – anbefalt term (skos:prefLabel) [[Begrep-anbefalt-term]]

[cols="30s,70d"]
|===
| _English name_ | _preferred term_
| URI |skos:prefLabel
| Verdiområde / _Range_ |rdf:langString
| Anvendelse / _Usage note_ | Egenskapen brukes til å oppgi en https://termbasen.standard.no/term/167505078703413/nb?origin=%2Fsearch-results%3FsearchText%3Danbefalt%2Bterm%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[anbefalt term]. Egenskapen bør gjentas når termen finnes på flere skriftspråk.

_This property is used to specify a https://termbasen.standard.no/term/167505078703413/nb?origin=%2Fsearch-results%3FsearchText%3Danbefalt%2Bterm%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[preferred term]. This property should be repeated for parallel language versions of the term._
| Multiplisitet / _Multiplicity_ |2..n
| Kravnivå / _Requirement level_ |Obligatorisk / _Mandatory_
| Merknad 1 / _Note 1_ | Anbefalt term skal finnes på både bokmål og nynorsk. Det skal være maksimum én per skriftspråk.

_The preferred term shall be in both Norwegian bokmål and Norwegian nynorsk. There shall be maximum one per language._
| Merknad 2 / _Note 2_ | Det skal være minst én kombinasjon av anbefalt term og definisjon (direkte angivelse eller via definisjonsobjekt) som er på samme skriftspråk.

_There shall be minimum one combination of preferred term and definition (direct statement or via definition object) that are in the same language._
|===

Eksempel i RDF Turtle, for NAVs begrep 975 «mødrekvote»:
-----
<https://data.norge.no/concepts/6bd8baed-c9d7-4dbc-b850-78ceeebdc1d5> a skos:Concept ; # begrep
   skos:prefLabel "mødrekvote"@nb, "mødrekvote"@nn ; # anbefalt term
   .
-----

===== Begrep – definisjon (direkte angivelse) (skos:definition) [[Begrep-definisjon-direkte-angivelse]]

[cols="30s,70d"]
|===
| _English name_ | _definition (direct statement)_
| URI |skos:definition
| Verdiområde / _Range_ |rdf:langString
| Anvendelse / _Usage note_ | Egenskapen brukes til å oppgi https://termbasen.standard.no/term/167505060009870/nb?origin=%2Fsearch-results%3FsearchText%3Ddefinisjon%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[definisjonen] av et begrep, når det ikke er behov for å oppgi mer enn selve definisjonsteksten. Egenskapen bør gjentas når definisjonen finnes på flere skriftspråk.

_This property is used to specify the https://termbasen.standard.no/term/167505060009870/nb?origin=%2Fsearch-results%3FsearchText%3Ddefinisjon%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[definition] of a concept, when there is no need to specify more than the definition itself. This property should be repeated for parallel language versions of the definition._
| Multiplisitet / _Multiplicity_ |1..n
| Kravnivå / _Requirement level_ |Obligatorisk / _Mandatory_
| Merknad 1 / _Note 1_ | Det skal være minimum én definisjon (direkte angivelse eller via definisjonsobjekt) og maksimum én per skriftspråk.

_There shall be minimum one definition (direct statement or via definition object) and maximum one per language._
| Merknad 2 / _Note 2_ | Det skal være minst én kombinasjon av anbefalt term og definisjon (direkte angivelse eller via definisjonsobjekt) som er på samme skriftspråk.

_There shall be minimum one combination of preferred term and definition (direct statement or via definition object) that are in the same language._
|===

Eksempel i RDF Turtle, for NAVs begrep 975 «mødrekvote»:
-----
<https://data.norge.no/concepts/6bd8baed-c9d7-4dbc-b850-78ceeebdc1d5> a skos:Concept ; # begrep
   skos:definition "den delen av foreldrepengeperioden som er forbeholdt mor"@nb ; # definisjon, bokmål
   .
-----

===== Begrep – definisjon (via definisjonsobjekt) (euvoc:xlDefinition) [[Begrep-definisjon-via-definisjonsobjekt]]

[cols="30s,70d"]
|===
| _English name_ | _definition (via definition object)_
| URI |euvoc:xlDefinition
| Verdiområde / _Range_ |euvoc:XlNote
| Anvendelse / _Usage note_ | Egenskapen brukes til å oppgi https://termbasen.standard.no/term/167505060009870/nb?origin=%2Fsearch-results%3FsearchText%3Ddefinisjon%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[definisjonen] av et begrep, når det er behov for å oppgi mer enn definisjonsteksten. Egenskapen bør gjentas når definisjonen finnes på flere skriftspråk.

_This property is used to specify the https://termbasen.standard.no/term/167505060009870/nb?origin=%2Fsearch-results%3FsearchText%3Ddefinisjon%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[definition] to a concept, when there is a need to specify more than the definition. This property should be repeated for parallel language versions of the definition._
| Multiplisitet / _Multiplicity_ |1..n
| Kravnivå / _Requirement level_ |Obligatorisk / _Mandatory_
| Merknad 1 / _Note 1_ | Det skal være minimum én definisjon (direkte angivelse eller via definisjonsobjekt) og maksimum én per skriftspråk.

_There shall be minimum one definition (direct statement or via definition object) and maximum one per language._
| Merknad 2 / _Note 2_ | Det skal være minst én kombinasjon av anbefalt term og definisjon (direkte angivelse eller via definisjonsobjekt) som er på samme skriftspråk.

_There shall be minimum one combination of preferred term and definition (direct statement or via definition object) that are in the same language._
|===

Eksempel i RDF Turtle: Se under <<Definisjon>>.

===== Begrep – identifikator (dct:identifier) [[Begrep-identifikator]]

[cols="30s,70d"]
|===
| _English name_ | _identifier_
| URI |dct:identifier
| Verdiområde / _Range_ |xsd:anyURI
| Anvendelse / _Usage note_ | Egenskapen brukes til å oppgi identifikator til begrepet.

_This property is used to specify an identifier to the concept._
| Multiplisitet / _Multiplicity_ |1..n
| Kravnivå / _Requirement level_ |Obligatorisk / _Mandatory_
| Merknad  / _Note_ |  Se https://data.norge.no/guide/veileder-beskrivelse-av-datasett/#om-identifikator[Om identifikator (dct:identifer) i Veileder for beskrivelse av datasett osv.]

_See https://data.norge.no/guide/veileder-beskrivelse-av-datasett/#om-identifikator[Om identifikator (dct:identifer) i Veileder for beskrivelse av datasett osv.]_
|===

Eksempel i RDF Turtle, for NAVs begrep 975 «mødrekvote»:
-----
<https://data.norge.no/concepts/6bd8baed-c9d7-4dbc-b850-78ceeebdc1d5> a skos:Concept ; # begrep
   dct:identifier "https://data.norge.no/concepts/6bd8baed-c9d7-4dbc-b850-78ceeebdc1d5"^^xsd:anyURI ; # identifikator
   .
-----

===== Begrep – kontaktpunkt (dcat:contactPoint) [[Begrep-kontaktpunkt]]

[cols="30s,70d"]
|===
| _English name_ | _contact point_
| URI |dcat:contactPoint
| Verdiområde / _Range_ |vcard:Organization or vcard:Group
| Anvendelse / _Usage note_ | Egenskapen brukes til å oppgi kontaktpunkt som kan nås ved f.eks. spørsmål om begrepet.

_This property is used to specify a contact point which may be reached in case of e.g. questions about the concept._
| Multiplisitet / _Multiplicity_ |1..n
| Kravnivå / _Requirement level_ |Obligatorisk / _Mandatory_
| Merknad / _Note_ | Når det er ulike kontaktpunkter for ulike språk (f.eks. norske vs. internasjonale kontakter), skal det oppgis maks. ett kontaktpunkt per språk.

_When there are different contact points for different languages (e.g. Norwegian vs. international contacts), there shall be maximum one contact point per language._
|===

Eksempel i RDF Turtle, for NAVs begrep 975 «mødrekvote»:
-----
<https://data.norge.no/concepts/6bd8baed-c9d7-4dbc-b850-78ceeebdc1d5> a skos:Concept ; # begrep
   dcat:contactPoint [ a vcard:Organization ; # kontaktpunkt
   vcard:hasOrganizationName "NAV"@nb ; # navn
   vcard:hasEmail <mailto:begrepskatalogen@nav.no> ; ] ; # e-post
   .
-----

===== Begrep – publisert av (dct:publisher) [[Begrep-publisert-av]]

[cols="30s,70d"]
|===
| _English name_ | _publisher_
| URI |dct:publisher
| Verdiområde / _Range_ |org:Organization
| Anvendelse / _Usage note_ | Egenskapen brukes til å referere til virksomheten som har publisert begrepet.

_This property is used to refer to the organisation responsible for publishing the concept._
| Multiplisitet / _Multiplicity_ |1..1
| Kravnivå / _Requirement level_ |Obligatorisk / _Mandatory_
| Merknad / _Note_ | Virksomhetens identifikasjonsnummer bør brukes, for eksempel https://data.norge.no/concepts/f6639f5e-280e-4dbb-991e-3faca3bf622c[Enhetsregisterets organisasjonsnummer].

_The organization’s identifier should be used, e.g. the organization number registered in the Central Coordinating Register for Legal Entities (CCR)._
|===

Eksempel i RDF Turtle, for NAVs begrep 975 «mødrekvote»:
-----
<https://data.norge.no/concepts/6bd8baed-c9d7-4dbc-b850-78ceeebdc1d5> a skos:Concept ; # begrep
   dct:publisher <https://organization-catalog.fellesdatakatalog.digdir.no/organizations/889640782> ; # publisert av, med NAVs organisasjonsnummer
   .
-----

==== Anbefalte egenskaper for _Begrep_ [[Begrep-anbefalte-egenskaper]]

===== Begrep – ansvarlig virksomhet (dct:creator) [[Begrep-ansvarlig-virksomhet]]

[cols="30s,70d"]
|===
| _English name_ | _responsible organization_
| URI | dct:creator
| Verdiområde / _Range_ | org:Organization
| Anvendelse / _Usage note_ | Egenskapen brukes til å referere til virksomheten som er ansvarlig for beskrivelsen av begrepet, og som ikke er den samme som <<Begrep-publisert-av>>.

_This property is used to refer to the organization responsible for the description of the concept, which is not the same as <<Begrep-publisert-av>>._
| Multiplisitet / _Multiplicity_ |0..1
| Kravnivå / _Requirement level_ |Anbefalt / _Recommended_
|===

===== Begrep – dato gyldig fra og med (euvoc:startDate) [[Begrep-dato-gyldig-fra-og-med]]

[cols="30s,70d"]
|===
| _English name_ | _date valid from, inclusive_
| URI |euvoc:startDate
| Verdiområde / _Range_ |xsd:date
| Anvendelse / _Usage note_ | Egenskapen brukes til å oppgi hvilken dato begrepet er gyldig fra og med.

_This property is used to specify the date (inclusive) from which the concept is valid._
| Multiplisitet / _Multiplicity_ |0..1
| Kravnivå / _Requirement level_ |Anbefalt / _Recommended_
|===

Eksempel i RDF Turtle:
-----
<eksempel-begrep> a skos:Concept ;
   euvoc:startDate "2000-01-31"^^xsd:date ;
   .
-----

===== Begrep – dato gyldig til og med (euvoc:endDate) [[Begrep-dato-gyldig-til-og-med]]

[cols="30s,70d"]
|===
| _English name_ | _date valid through, inclusive_
| URI |euvoc:endDate
| Verdiområde / _Range_ |xsd:date
| Anvendelse / _Usage note_ | Egenskapen brukes til å oppgi hvilken dato begrepet er gyldig til og med.

_This property is used to specify the date (inclusively) through which the concept is valid._
| Multiplisitet / _Multiplicity_ |0..1
| Kravnivå / _Requirement level_ |Anbefalt / _Recommended_
|===

Eksempel i RDF Turtle:
-----
<eksempel-begrep> a skos:Concept ; # eksempel-begrep
   euvoc:endDate "2020-12-31"^^xsd:date ; # dato gyldig til og med
   .
-----

===== Begrep – dato opprettet (dct:created) [[Begrep-dato-opprettet]]

[cols="30s,70d"]
|===
| _English name_ | _date created_
| URI |dct:created
| Verdiområde / _Range_ |xsd:date
| Anvendelse / _Usage note_ | Egenskapen brukes til å oppgi datoen da begrepet ble opprettet.

_This property is used to specify the date when the concept was created._
| Multiplisitet / _Multiplicity_ |0..1
| Kravnivå / _Requirement level_ |Anbefalt / _Recommended_
|===

Eksempel i RDF Turtle:
-----
<eksempel-begrep> a skos:Concept ; # eksempel-begrep
   dct:created "2000-01-31"^^xsd:date ; # dato gyldig fra og med
   .
-----

===== Begrep – dato sist oppdatert (dct:modified) [[Begrep-dato-sist-oppdatert]]

[cols="30s,70d"]
|===
| _English name_ | _date last modified_
| URI |dct:modified
| Verdiområde / _Range_ |xsd:date
| Anvendelse / _Usage note_ | Egenskapen brukes til å oppgi datoen da begrepet sist ble oppdatert.

_This property is used to specify the date when the concept was last modified._
| Multiplisitet / _Multiplicity_ |0..1
| Kravnivå / _Requirement level_ |Anbefalt / _Recommended_
|===

Eksempel i RDF Turtle:
-----
<eksempel-begrep> a skos:Concept ; # eksempel-begrep
   dct:modified "2020-05-31"^^xsd:date ; # dato sist oppdatert
   .
-----

===== Begrep – fagområde (dct:subject) [[Begrep-fagområde]]


[cols="30s,70d"]
|===
| _English name_ | _subject field_
| URI |dct:subject
| Verdiområde / _Range_ |rdf:langString or skos:Concept
| Anvendelse / _Usage note_ | Egenskapen brukes til å oppgi https://termbasen.standard.no/term/167505060700241/nb?origin=%2Fsearch-results%3FsearchText%3Dfagomr%25C3%25A5de%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[fagområde] som begrepet kan grupperes/klassifiseres under. Dette oppgis enten som tekst med språkkode eller som kodet verdi. Hvis tekst brukes, og når teksten finnes på flere skriftspråk, bør egenskapen gjentas for hvert skriftspråk.

_This property is used to specify a https://termbasen.standard.no/term/167505060700241/nb?origin=%2Fsearch-results%3FsearchText%3Dfagomr%25C3%25A5de%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[domain] (subject field) under which the concept may be grouped/classified, either as a text with language code or as a coded value. When text is used, the property should be repeated for parallel language versions of the text._
| Multiplisitet / _Multiplicity_ |0..n
| Kravnivå / _Requirement level_ |Anbefalt / _Recommended_
| Merknad / _Note_ | Fagområde kan representere en akademisk disiplin, et bruksområde, et produkt, en tjenestekjede eller lignende.

_A subject field may represent an academic discipline, an application area, a product, a service chain or suchlike._
|===

Eksempel i RDF Turtle:
-----
<eksempel-begrep> a skos:Concept ; # eksempel-begrep
   dct:subject "terminologi"@nb, "terminologi"@nn, "terminology"@en ; # fagområde
   .
-----

===== Begrep – merknad (skos:scopeNote) [[Begrep-merknad]]

[cols="30s,70d"]
|===
| _English name_ | _note_
| URI |skos:scopeNote
| Verdiområde / _Range_ |rdf:langString
| Anvendelse / _Usage note_ | Egenskapen brukes til å oppgi utfyllende forklaring til begrepet. Egenskapen bør gjentas når teksten finnes på flere skriftspråk.

_This property is used to specify notes about the concept. The property should be repeated for parallel language versions of the text._
| Multiplisitet / _Multiplicity_ |0..n
| Kravnivå / _Requirement level_ |Anbefalt / _Recommended_
|===

Eksempel i RDF Turtle, for NAVs begrep 975 «mødrekvote»:
-----
<https://data.norge.no/concepts/6bd8baed-c9d7-4dbc-b850-78ceeebdc1d5> a skos:Concept ; # begrep
   skos:scopeNote "Deler av mødrekvoten er bundet i tid avhengig av når fødsel skjer."@en ; # merknad
   .
-----


===== Begrep – tillatt term (skos:altLabel) [[Begrep-tillatt-term]]

[cols="30s,70d"]
|===
| _English name_ | _admitted term_
| URI |skos:altLabel
| Verdiområde / _Range_ |rdf:langString
| Anvendelse / _Usage note_ | Egenskapen brukes til å oppgi https://termbasen.standard.no/term/167505073502479/nb?origin=%2Fsearch-results%3FsearchText%3Dtillatt%2Bterm%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[tillatt term] til begrepet. Egenskapen bør gjentas når termen finnes på flere skriftspråk.

_This property is used to specify an https://termbasen.standard.no/term/167505073502479/nb?origin=%2Fsearch-results%3FsearchText%3Dtillatt%2Bterm%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[admitted term] to a concept. This property should be repeated for parallel language versions of the term._
| Multiplisitet / _Multiplicity_ |0..n
| Kravnivå / _Requirement level_ |Anbefalt / _Recommended_
|===

Eksempel i RDF Turtle, for NAVs begrep 1091 («autorisering»):
-----
<https://data.norge.no/concepts/cc1482f9-0244-3008-88b7-a833e2c8f6e1> a skos:Concept ; # begrep
   skos:altLabel "autorisasjon"@nb ; # tillatt term
   .
-----

==== Valgfrie egenskaper for _Begrep_ [[Begrep-valgfrie-egenskaper]]

===== Begrep – datastrukturterm (skosno:dataStructureLabel) [[Begep-datastrukturterm]]

[cols="30s,70d"]
|===
| _English name_ | _data structure label_
| URI |skosno:dataStructureLabel
| Verdiområde / _Range_ |rdfs:Literal
| Anvendelse / _Usage note_ | Egenskapen brukes til å oppgi datastrukturterm for begrepet.

_This property is used to specify a data structure label._
| Multiplisitet / _Multiplicity_ |0..n
| Kravnivå / _Requirement level_ |Valgfri / _Optional_
|===

Eksempel i RDF Turtle, for Skatteetatens begrep «fysisk person»:
-----
<http://begrepskatalogen/begrep/b57408ba-d96a-11e6-8d9b-005056821322> a skos:Concept ; # begrep
   skosno:dataStructureLabel "fysiskPerson" ; # datastrukturterm
   .
-----

===== Begrep – eksempel (skos:example) [[Begrep-eksempel]]

[cols="30s,70d"]
|===
| _English name_ | _example_
| URI |skos:example
| Verdiområde / _Range_ |rdf:langString
| Anvendelse / _Usage note_ | Egenskapen brukes til å oppgi eksempler på begrepet. Egenskapen bør gjentas når teksten finnes på flere skriftspråk.

_This property is used to specify examples of the concept. This property should be repeated for parallel language versions of the text._
| Multiplisitet / _Multiplicity_ |0..n
| Kravnivå / _Requirement level_ |Valgfri / _Optional_
|===

Eksempel i RDF Turtle, hentet 2022-12-09 fra Termbasen til Standard Norge, for begrep https://termbasen.standard.no/term/167505060300135/nb?origin=%2Fsearch-results%3FsearchText%3Dindividualbegrep%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[«individualbegrep»]:
-----
<hentetFraSNORRE> a skos:Concept ;
   skos:example "‘Saturn’, ‘Eiffeltårnet’, ‘Månen’, ‘serienummer FRHR603928’, ‘Nobelpris i fysikk 2016’."@nb ;
     .
-----

===== Begrep – er del av (xkos:isPartOf) [[Begrep-er-del-av]]

[cols="30s,70d"]
|===
| _English name_ | _is part of_
| URI |xkos:isPartOf
| Verdiområde / _Range_ |skos:Concept
| Anvendelse / _Usage note_ | Egenskapen brukes til å knytte begrepet til et annet begrep som dette begrepet er del av. Begrepet er et https://termbasen.standard.no/term/167505058207722/nb?origin=%2Fsearch-results%3FsearchText%3Ddelbegrep%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[delbegrep], og det andre begrepet er https://termbasen.standard.no/term/167505059008991/nb?origin=%2Fsearch-results%3FsearchText%3Dhelhetsbegrep%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[helhetsbegrepet], i en partitiv relasjon mellom disse.

_This property is used to refer to the concept that this concept is a part of. This concept is a https://termbasen.standard.no/term/167505058207722/nb?origin=%2Fsearch-results%3FsearchText%3Ddelbegrep%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[partitive concept] and the other concept is the https://termbasen.standard.no/term/167505059008991/nb?origin=%2Fsearch-results%3FsearchText%3Dhelhetsbegrep%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[comprehensive concept], in a partitive concept relation between the two concepts._
| Multiplisitet / _Multiplicity_ |0..n
| Kravnivå / _Requirement level_ |Valgfri / _Optional_
| Merknad 1 / _Note 1_ | Egenskapen/relasjonen kan også leses som «har helhetsbegrep».

_This property/relation may also be read as “has comprehensive concept”._
| Merknad 2 / _Note 2_ | Denne egenskapen/relasjonen er den motsatte av <<Begrep-inneholder>>.

_This property/relation is the inverse of <<Begrep-inneholder>>._
| Merknad 3 / _Note 3_ | Bruk <<Begrep-har-partitiv-begrepsrelasjon>> når det er behov for å oppgi https://termbasen.standard.no/term/167505058508031/nb?origin=%2Fsearch-results%3FsearchText%3Dinndelingskriterium%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[inndelingskriterium].

_Use <<Begrep-har-partitiv-begrepsrelasjon>> when there is a need to specify the https://termbasen.standard.no/term/167505058508031/nb?origin=%2Fsearch-results%3FsearchText%3Dinndelingskriterium%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[criterion of subdivision]._
|===

Eksempel i RDF Turtle, for NAVs begrep 975 «mødrekvote»:
-----
<https://data.norge.no/concepts/6bd8baed-c9d7-4dbc-b850-78ceeebdc1d5> a skos:Concept ; # begrep  «mødrekvote»
   xkos:isPartOf <https://data.norge.no/concepts/4729eca4-f145-4518-8309-3e02a84dfc55> ; # er del av «foreldrepengeperiode»
     .
-----

===== Begrep – er erstattet av (dct:isReplacedBy) [[Begrep-er-erstattet-av]]

[cols="30s,70d"]
|===
| _English name_ | _is replaced by_
| URI |dct:isReplacedBy
| Verdiområde / _Range_ |skos:Concept
| Anvendelse / _Usage note_ | Egenskapen brukes til å referere til et annet begrep som dette begrepet er erstattet av.

_This property is used to refer to a concept that this concept is replaced by._
| Multiplisitet / _Multiplicity_ |0..n
| Kravnivå / _Requirement level_ |Valgfri / _Optional_
| Merknad / _Note_ | Denne egenskapen/relasjonen er den motsatte av <<Begrep-erstatter>>.

_This property/relation is the inverse of <<Begrep-erstatter>>._
|===

Eksempel i RDF Turtle, for SSBs begrep «landbakgrunn»:
-----
<https://www.ssb.no/a/metadata/conceptvariable/vardok/123/nb> a skos:Concept ; # begrep
   dct:isReplacedBy <https://www.ssb.no/a/metadata/conceptvariable/vardok/1919/nb> ; # er erstattet av
   .
-----

===== Begrep – er fra-begrep i (skosno:isFromConceptIn) [[Begrep-er-fra-begrep-i]]

[cols="30s,70d"]
|===
| _English name_ | _is from-concept in_
| URI |skosno:isFromConceptIn
| Verdiområde / _Range_ |skosno:AssociativeConceptRelation
| Anvendelse / _Usage note_ | Egenskapen brukes til å oppgi en https://termbasen.standard.no/term/167505058508115/nb?origin=%2Fsearch-results%3FsearchText%3Dassosiativ%2Bbegrepsrelasjon%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[assosiativ begrepsrelasjon] som begrepet har med et annet begrep, når det er behov for å beskrive relasjonsrollen til dette begrepet.

_This property is used to refer to an https://termbasen.standard.no/term/167505058508115/nb?origin=%2Fsearch-results%3FsearchText%3Dassosiativ%2Bbegrepsrelasjon%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[associative relation] that this concept has with another concept, when there is a need to describe the relation role of this concept._
| Multiplisitet / _Multiplicity_ |0..n
| Kravnivå / _Requirement level_ |Valgfri / _Optional_
|===

Eksempel i RDF Turtle: Se under <<Assosiativ-begrepsrelasjon>>.

===== Begrep – er relatert til (skos:related) [[Begrep-er-relatert-til]]

[cols="30s,70d"]
|===
| _English name_ | _is related to_
| URI |skos:related
| Verdiområde / _Range_ |skos:Concept
| Anvendelse / _Usage note_ | Egenskapen brukes til å referere til et annet begrep som begrepet er relatert til, når det ikke er behov for å beskrive relasjonsrollen til dette begrepet.

_This property is used to refer to a concept that this concept is related to, when there is no need to describe the relation role of this concept._
| Multiplisitet / _Multiplicity_ |0..n
| Kravnivå / _Requirement level_ |Valgfri / _Optional_
| Merknad 1 / _Note 1_ | Egenskapen/relasjonen kan også leses som «har assosiert begrep».

_This property/relation may also be read as “has associated concept”._
| Merknad 2 / _Note 2_ | Bruk heller en av de andre semantisk mer presise assosiative begrepsrelasjonene.

_Use rather one of the other semantically more precise associative concept relations._
| Merknad 3 / _Note 3_ | Bruk <<Begrep-er-fra-begrep-i>> når det er behov for å oppgi relasjonsrollen til dette begrepet.

_Use <<Begrep-er-fra-begrep-i>> when there is a need to specify the relation role of this concept._
|===

Eksempel i RDF Turtle, for NAVs begrep 170 «medlem i folketrygden»:
-----
<https://data.norge.no/concepts/68950551-3fec-3fb4-a802-8127bac322c2> a skos:Concept ; # begrep «medlem i folketrygden»
   skos:related <https://data.norge.no/concepts/d649801d-b47d-4d00-9470-35275c4ace00> ; # er relatert til «trygdeavgift»
   .
-----

===== Begrep – erstatter (dct:replaces) [[Begrep-erstatter]]

[cols="30s,70d"]
|===
| _English name_ | _replaces_
| URI |dct:replaces
| Verdiområde / _Range_ |skos:Concept
| Anvendelse / _Usage note_ | Egenskapen brukes til å referere til et annet begrep som dette begrepet erstatter.

_This property is used to refer to a concept that this concept replaces._
| Multiplisitet / _Multiplicity_ |0..n
| Kravnivå / _Requirement level_ |Valgfri / _Optional_
| Merknad / _Note_ | Denne egenskapen/relasjonen er den motsatte av <<Begrep-er-erstattet-av>>.

_This property/relation is the inverse of <<Begrep-er-erstattet-av>>._
|===

Eksempel i RDF Turtle, for SSBs begrep «landbakgrunn»:
-----
<https://www.ssb.no/a/metadata/conceptvariable/vardok/1919/nb> a skos:Concept ; # begrep
   dct:replaces <https://www.ssb.no/a/metadata/conceptvariable/vardok/123/nb> ; # erstatter
     .
-----

===== Begrep – frarådd term (skos:hiddenLabel) [[Begrep-frarådd-term]]

[cols="30s,70d"]
|===
| _English name_ | _deprecated term_
| URI |skos:hiddenLabel
| Verdiområde / _Range_ |rdf:langString
| Anvendelse / _Usage note_ | Egenskapen brukes til å oppgi en https://termbasen.standard.no/term/167505072601390/nb?origin=%2Fsearch-results%3FsearchText%3Dfrar%25C3%25A5dd%2Bterm%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[frarådd term]. Egenskapen bør gjentas når termen finnes på flere skriftspråk.

_This property is used to specify a https://termbasen.standard.no/term/167505072601390/nb?origin=%2Fsearch-results%3FsearchText%3Dfrar%25C3%25A5dd%2Bterm%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[deprecated term]. This property should be repeated for parallel language versions of the term._
| Multiplisitet / _Multiplicity_ |0..n
| Kravnivå / _Requirement level_ |Valgfri / _Optional_
|===

Eksempel i RDF Turtle, for NAVs begrep 936 «tiltakspenger»:
-----
<https://data.norge.no/concepts/a9dc3c9c-df22-3cd4-a30b-b30b9de009ce> a skos:Concept ; # begrep «tiltakspenger»
   skos:hiddenLabel "individstønad"@nb ; # frarådd term
   .
-----

===== Begrep – generaliserer (xkos:generalizes) [[Begrep-generaliserer]]

[cols="30s,70d"]
|===
| _English name_ | _generalizes_
| URI |xkos:generalizes
| Verdiområde / _Range_ |skos:Concept
| Anvendelse / _Usage note_ | Egenskapen brukes til å referere til et annet begrep som dette begrepet generaliserer. Begrepet er https://termbasen.standard.no/term/167505059909767/nb?origin=%2Fsearch-results%3FsearchText%3Dgenerisk%2Bbegrep%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[det generiske begrepet] og det andre begrepet er https://termbasen.standard.no/term/167505058608367/nb?origin=%2Fsearch-results%3FsearchText%3Dspesifikt%2Bbegrep%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[det spesifikke begrepet], i en generisk relasjon mellom disse.

_This property is used to refer to another concept that this concept generalizes. This concept is the https://termbasen.standard.no/term/167505059909767/nb?origin=%2Fsearch-results%3FsearchText%3Dgenerisk%2Bbegrep%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[generic concept] and the other concept is the https://termbasen.standard.no/term/167505058608367/nb?origin=%2Fsearch-results%3FsearchText%3Dspesifikt%2Bbegrep%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[specific concept], in a generic concept relation between the two concepts._
| Multiplisitet / _Multiplicity_ |0..n
| Kravnivå / _Requirement level_ |Valgfri / _Optional_
| Merknad 1 / _Note 1_ | Egenskapen/relasjonen kan også leses som «har underbegrep».

_This property/relation may also be read as “has specific concept”._
| Merknad 2 / _Note 2_ | Egenskapen/relasjonen er den motsatte av <<Begrep-spesialiserer>>.

_This property/relation is the inverse of <<Begrep-spesialiserer>>._
| Merknad 3 / _Note 3_ | Bruk <<Begrep-har-generisk-begrepsrelasjon>> når det er behov for å oppgi https://termbasen.standard.no/term/167505058508031/nb?origin=%2Fsearch-results%3FsearchText%3Dinndelingskriterium%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[inndelingskriterium].

_Use <<Begrep-har-generisk-begrepsrelasjon>> when there is a need to specify the https://termbasen.standard.no/term/167505058508031/nb?origin=%2Fsearch-results%3FsearchText%3Dinndelingskriterium%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[criterion of subdivision]._
|===

Eksempel i RDF Turtle, for NAVs begrep 625 «ytelsesperiode»:
-----
<https://data.norge.no/concepts/680b83b6-46f5-30f2-96f7-e36c4e5cf3d1> a skos:Concept ; # begrep «ytelsesperiode»
   xkos:generalizes <https://data.norge.no/concepts/4729eca4-f145-4518-8309-3e02a84dfc55> ; # generaliserer «foreldrepengeperiode»
   .
-----

===== Begrep – har eksakt samsvar med (skos:exactMatch) [[Begrep-har-eksakt-samsvar-med]]

[cols="30s,70d"]
|===
| _English name_ | _has exact match with_
| URI |skos:exactMatch
| Verdiområde / _Range_ |skos:Concept
| Anvendelse / _Usage note_ | Egenskapen brukes til å referere til et annet begrep der det er eksakt samsvar mellom disse begrepene.

_This property is used to refer to another concept where there is an exact match between the two concepts._
| Multiplisitet / _Multiplicity_ |0..n
| Kravnivå / _Requirement level_ |Valgfri / _Optional_
|===

Eksempel i RDF Turtle:
-----
<eksempel-begrep1> a skos:Concept ; # eksempel-begrep
   skos:exactMatch <eksempel-begrep2> ; # har eksakt samsvar med
   .
-----

===== Begrep – har generisk begrepsrelasjon (skosno:hasGenericConceptRelation) [[Begrep-har-generisk-begrepsrelasjon]]

[cols="30s,70d"]
|===
| _English name_ | _has generic concept relation_
| URI |skosno:hasGenericConceptRelation
| Verdiområde / _Range_ |skosno:GenericConceptRelation
| Anvendelse / _Usage note_ | Egenskapen brukes til å oppgi en https://termbasen.standard.no/term/167505058307926/nb?origin=%2Fsearch-results%3FsearchText%3Dgenerisk%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[generisk begrepsrelasjon] som begrepet har med et annet begrep, når det er behov for å oppgi https://termbasen.standard.no/term/167505058508031/nb?origin=%2Fsearch-results%3FsearchText%3Dinndelingskriterium%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[inndelingskriterium].

_This property is used to refer to a https://termbasen.standard.no/term/167505058307926/nb?origin=%2Fsearch-results%3FsearchText%3Dgenerisk%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[generic concept relation] that this concept has with another concept, in order to specify the https://termbasen.standard.no/term/167505058508031/nb?origin=%2Fsearch-results%3FsearchText%3Dinndelingskriterium%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[criterion of subdivision]._
| Multiplisitet / _Multiplicity_ |0..n
| Kravnivå / _Requirement level_ |Valgfri / _Optional_
|===

Eksempel i RDF Turtle: Se under <<Generisk-begrepsrelasjon>>.

===== Begrep – har nært samsvar med (skos:closeMatch) [[Begrep-har-nært-samsvar-med]]

[cols="30s,70d"]
|===
| _English name_ | _has close match with_
| URI |skos:closeMatch
| Verdiområde / _Range_ |skos:Concept
| Anvendelse / _Usage note_ | Egenskapen brukes til å referere til et annet begrep der det er nært samsvar mellom disse begrepene.

_This property is used to refer to another concept where there is a close match between the two concepts._
| Multiplisitet / _Multiplicity_ |0..n
| Kravnivå / _Requirement level_ |Valgfri / _Optional_
|===

Eksempel i RDF Turtle:
-----
<eksempel-begrep1> a skos:Concept ; # begrep
   skos:closeMatch <eksempel-begrep2> ; # har nært samsvar med
   .
-----

===== Begrep – har partitiv begrepsrelasjon (skosno:hasPartitiveConceptRelation) [[Begrep-har-partitiv-begrepsrelasjon]]

[cols="30s,70d"]
|===
| _English name_ | _has partitive concept relation_
| URI |skosno:hasPartitiveConceptRelation
| Verdiområde / _Range_ |skosno:PartitiveConceptRelation
| Anvendelse / _Usage note_ | Egenskapen brukes til å oppgi en https://termbasen.standard.no/term/167505058808598/nb?origin=%2Fsearch-results%3FsearchText%3Dpartitiv%2Bbegrepsrelasjon%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[partitiv begrepsrelasjon] som begrepet har med et annet begrep, når det er behov for å oppgi https://termbasen.standard.no/term/167505058508031/nb?origin=%2Fsearch-results%3FsearchText%3Dinndelingskriterium%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[inndelingskriterium].

_This property is used to refer to a https://termbasen.standard.no/term/167505058808598/nb?origin=%2Fsearch-results%3FsearchText%3Dpartitiv%2Bbegrepsrelasjon%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[partitive concept relation] that this concept has with another concept, when there is a need to specify the https://termbasen.standard.no/term/167505058508031/nb?origin=%2Fsearch-results%3FsearchText%3Dinndelingskriterium%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[criterion of subdivision]._
| Multiplisitet / _Multiplicity_ |0..n
| Kravnivå / _Requirement level_ |Valgfri / _Optional_
|===

Eksempel i RDF Turtle: Se under <<Partitiv-begrepsrelasjon>>.

===== Begrep – inneholder (xkos:hasPart) [[Begrep-inneholder]]

[cols="30s,70d"]
|===
| _English name_ | _has part_
| URI |xkos:hasPart
| Verdiområde / _Range_ |skos:Concept
| Anvendelse / _Usage note_ | Egenskapen brukes til å referere til et annet begrep som dette begrepet inneholder. Begrepet er https://termbasen.standard.no/term/167505059008991/nb?origin=%2Fsearch-results%3FsearchText%3Dhelhetsbegrep%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[helhetsbegrepet] og det andre begrepet https://termbasen.standard.no/term/167505058207722/nb?origin=%2Fsearch-results%3FsearchText%3Ddelbegrep%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[delbegrepet], i en partitiv relasjon mellom disse.

_This property is used to refer to the concept that this concept has as a part. This concept is the https://termbasen.standard.no/term/167505059008991/nb?origin=%2Fsearch-results%3FsearchText%3Dhelhetsbegrep%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[comprehensive concept] and the other concept is the https://termbasen.standard.no/term/167505058207722/nb?origin=%2Fsearch-results%3FsearchText%3Ddelbegrep%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[partitive concept], in a partitive concept relation between the two concepts._
| Multiplisitet / _Multiplicity_ |0..n
| Kravnivå / _Requirement level_ |Valgfri / _Optional_
| Merknad 1 / _Note 1_  | Egenskapen/relasjonen kan også leses som «har delbegrep».

_This property/relation may also be read as “has partitive concept”._
| Merknad 2 / _Note 2_  | Denne egenskapen/relasjonen er den motsatte av <<Begrep-er-del-av>>.

_This property/relation is the inverse of <<Begrep-er-del-av>>._
| Merknad 3 / _Note 3_  | Bruk <<Begrep-har-partitiv-begrepsrelasjon>> når det er behov for å oppgi https://termbasen.standard.no/term/167505058508031/nb?origin=%2Fsearch-results%3FsearchText%3Dinndelingskriterium%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[inndelingskriterium].

_Use <<Begrep-har-partitiv-begrepsrelasjon>> when there is a need to specify the https://termbasen.standard.no/term/167505058508031/nb?origin=%2Fsearch-results%3FsearchText%3Dinndelingskriterium%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[criterion of subdivision]._
|===

Eksempel i RDF Turtle, for NAVs begrep 974 «foreldrepengeperiode»:
-----
<https://data.norge.no/concepts/4729eca4-f145-4518-8309-3e02a84dfc55> a skos:Concept ; # begrep «foreldrepengeperiode»
   xkos:hasPart # inneholder
      <https://data.norge.no/concepts/6bd8baed-c9d7-4dbc-b850-78ceeebdc1d5> , # «mødrekvote»
      <https://data.norge.no/concepts/13a8697d-177b-499b-8d22-9cee6741c025> , # «fellesperiode»
      <https://data.norge.no/concepts/32d18d0e-c9d4-4785-b1e8-3612ffca8fb7> ; # «fedrekvote»
     .
-----

===== Begrep – inngår i begrepssamling (uneskos:memberOf) [[Begrep-inngår-i]]

[cols="30s,70d"]
|===
| _English name_ | _member of_
| URI |uneskos:memberOf
| Verdiområde / _Range_ |skos:Collection
| Anvendelse / _Usage note_ | Egenskapen brukes til å referere til en begrepssamling der begrepet inngår.

_This property is used to refer to the collection that this concept is a member of._
| Multiplisitet / _Multiplicity_ |0..n
| Kravnivå / _Requirement level_ |Valgfri / _Optional_
| Merknad / _Note_ | Denne egenskapen/relasjonen er den motsatte av <<Begrepssamling-inneholder-begrep>>.

_This property/relation is the inverse of <<Begrepssamling-inneholder-begrep>>._
|===

Eksempel i RDF Turtle:
-----
<eksempel-begrep> a skos:Concept ; # eksempel-begrep
   uneskos:memberOf <eksempel-begrepssamling> ; # inngår i begrepssamling
     .
-----

===== Begrep – se også (rdfs:seeAlso) [[Begrep-se-også]]

[cols="30s,70d"]
|===
| _English name_ | _see also_
| URI |rdfs:seeAlso
| Verdiområde / _Range_ |skos:Concept
| Anvendelse / _Usage note_ | Egenskapen brukes til å referere til et annet begrep som dette begrepet har en «se også»-relasjon til.

_This property is used to refer to another concept that this concept has a “see also”-relation with._
| Multiplisitet / _Multiplicity_ |0..n
| Kravnivå / _Requirement level_ |Valgfri / _Optional_
|===

Eksempel i RDF Turtle:
-----
<eksempel-begrep> a skos:Concept ; # eksempel-begrep
   rdfs:seeAlso <et-annet-eksempel-begrep> ; # se også
   .
-----

===== Begrep – spesialiserer (xkos:specializes) [[Begrep-spesialiserer]]

[cols="30s,70d"]
|===
| _English name_ | _specializes_
| URI |xkos:specializes
| Verdiområde / _Range_ |skos:Concept
| Anvendelse / _Usage note_ | Egenskapen brukes til å referere til et annet begrep som dette begrepet spesialiserer. Begrepet er https://termbasen.standard.no/term/167505058608367/nb?origin=%2Fsearch-results%3FsearchText%3Dspesifikt%2Bbegrep%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[det spesifikke begrepet] og det andre begrepet er https://termbasen.standard.no/term/167505059909767/nb?origin=%2Fsearch-results%3FsearchText%3Dgenerisk%2Bbegrep%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[det generiske begrepet], i en generisk relasjon mellom disse.

_This property is used to refer to another concept that this concept specializes. This concept is the https://termbasen.standard.no/term/167505058608367/nb?origin=%2Fsearch-results%3FsearchText%3Dspesifikt%2Bbegrep%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[specific concept] and the other concept is the https://termbasen.standard.no/term/167505059909767/nb?origin=%2Fsearch-results%3FsearchText%3Dgenerisk%2Bbegrep%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[generic concept], in a generic concept relation between the two concepts._
| Multiplisitet / _Multiplicity_ |0..n
| Kravnivå / _Requirement level_ |Valgfri / _Optional_
| Merknad 1 / _Note 1_  | Egenskapen/relasjonen kan også leses som «har overbegrep».

_This property/relation may also be read as “has generic concept”._
| Merknad 2 / _Note 2_  | Egenskapen/relasjonen er den motsatte av <<Begrep-generaliserer>>.

_This property/relation is the inverse of <<Begrep-generaliserer>>._
| Merknad 3 / _Note 3_  | Bruk <<Begrep-har-generisk-begrepsrelasjon>> når det er behov for å oppgi https://termbasen.standard.no/term/167505058508031/nb?origin=%2Fsearch-results%3FsearchText%3Dinndelingskriterium%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[inndelingskriterium].

_Use <<Begrep-har-generisk-begrepsrelasjon>> when there is a need to specify the https://termbasen.standard.no/term/167505058508031/nb?origin=%2Fsearch-results%3FsearchText%3Dinndelingskriterium%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100[criterion of subdivision]._
|===

Eksempel i RDF Turtle, for NAVs begrep 975 «mødrekvote»:
-----
<https://data.norge.no/concepts/6bd8baed-c9d7-4dbc-b850-78ceeebdc1d5> a skos:Concept ; # begrep «mødrekvote»
   xkos:specializes <https://data.norge.no/concepts/4729eca4-f145-4518-8309-3e02a84dfc55> ; # spesialiserer «foreldrepengeperiode»
   .
-----

===== Begrep – status (euvoc:status) [[Begrep-status]]

[cols="30s,70d"]
|===
| _English name_ | _status_
| URI |euvoc:status
| Verdiområde / _Range_ |skos:Concept or rdf:langString
| Anvendelse / _Usage note_ | Egenskapen brukes til å oppgi status til et begrep, enten som kodet verdi eller som tekst med språkkode. Hvis tekst brukes, og hvis teksten finnes i flere skriftspråk, bør egenskapen gjentas for hvert språk. Hvis kodet verdi brukes, skal egenskapen ha kun én verdi.

_This property is used to specify the status of the concept, as text with language code or as coded value. If text is used, this property should be repeated for parallel language versions of the text. If coded value is used, the property shall have only one value._
| Multiplisitet / _Multiplicity_ |0..1 når skos:Concept brukes og 0..n når rdf:langString brukes

_0..1 when skos:Concept is used and 0..n when rdf:langString is used_
| Kravnivå / _Requirement level_ |Valgfri / _Optional_
| Merknad / _Note_ | Når begrepsbeskrivelsen gjøres tilgjengelig utenfor virksomheten, hvis en av kategoriene i EUs kontrollerte vokabular https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/concept-status[Concept status] passer til begrepets status, skal egenskapen referere til den aktuelle kategorien.

_When making the concept description available outside the organization, if one of the categories in EU’s https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/concept-status[Concept status] is suitable for the status of the concept, this property shall refer to that category._
|===

Eksempel i RDF Turtle, for NAVs begrep 975 «mødrekvote»:
-----
<https://data.norge.no/concepts/6bd8baed-c9d7-4dbc-b850-78ceeebdc1d5> a skos:Concept ; # begrep
   euvoc:status <http://publications.europa.eu/resource/authority/concept-status/CURRENT> ; # status
   .
-----

===== Begrep – verdiområde (skosno:valueRange) [[Begrep-verdiområde]]

[cols="30s,70d"]
|===
| _English name_ | _value range_
| URI |skosno:valueRange
| Verdiområde / _Range_ |rdf:langString or xsd:anyURI
| Anvendelse / _Usage note_ | Egenskapen brukes til å oppgi verdiområde, oppgitt som tekst og/eller referanse til der dette er spesifisert. Hvis tekst brukes, og hvis teksten finnes på flere skriftspråk, bør egenskapen gjentas for hvert språk.

_This property is used to specify the value range of a concept, as text and/or as reference to where this is specified. If text is used, this property should be repeated for parallel language versions of the text._
| Multiplisitet / _Multiplicity_ |0..n
| Kravnivå / _Requirement level_ |Valgfri / _Optional_
|===

Eksempel i RDF Turtle, for SSBs begrep «sivilstand»:
-----
<sivilstand> a skos:Concept ; # begrep
   skosno:range "Standard for sivilstand"@nb , "Standard for sivilstand"@nn , "Classification of marital status"@en ; # verdiområde, som tekst
   skosno:range <https://www.ssb.no/klass/klassifikasjoner/19> ; # verdiområde, som lenke
     .
-----

===== Begrep – versjonsnummer (owl:versionInfo) [[Begrep-versjonsnummer]]

[cols="30s,70d"]
|===
| _English name_ | _version number_
| URI | owl:versionInfo
| Verdiområde / _Range_ | rdfs:Literal
| Anvendelse / _Usage note_ | Egenskapen brukes til å oppgi versjonsnummer til et begrep.

_This property is used to specify the version number of the concept._
| Multiplisitet / _Multiplicity_ |0..1
| Kravnivå / _Requirement level_ | Valgfri / _Optional_
|===

Eksempel i RDF Turtle:
-----
<eksempel-begrep> a skos:Concept ; # eksempel-begrep
   owl:versionInfo "1.0.1" ; # versjonsnummer
   .
-----

===== Begrep – versjonsnote (adms:versionNotes) [[Begrep-versjonsnote]]

[cols="30s,70d"]
|===
| _English name_ | _version notes_
| URI | adms:versionNotes
| Verdiområde / _Range_ |rdf:langString
| Anvendelse / _Usage note_ | Egenskapen brukes til å oppgi versjonsnoter til en versjon av et begrep. Egenskapen bør gjentas når teksten finnes på flere skriftspråk.

_This property is used to specify version notes about the version. This property should be repeated for parallel language versions of the text._
| Multiplisitet / _Multiplicity_ |0..n
| Kravnivå / _Requirement level_ |Valgfri / _Optional_
|===

Eksempel i RDF Turtle:
-----
<eksempel-begrep> a skos:Concept ; # eksempel-begrep
   adms:versionNotes "Nå med «tullebegrep» også som en lovlig verdi."@nb ; # versjonsnote
   .
-----
