=== Eksempler på begrepsbeskrivelser [[Del1-eksempler-på-begrepsbeskrivelser]]

|===
a|*Eksempel på en begrepsbeskrivelse med kun obligatoriske opplysninger*, hentet fra Felles datakatalog, 2022-11-25, for begrepet https://data.norge.no/concepts/6bd8baed-c9d7-4dbc-b850-78ceeebdc1d5[«mødrekvote» &#x29C9;, window="_blank", role="ext-link"]:

* *anbefalt term*: «mødrekvote» (bokmål), «mødrekvote» (nynorsk)
* *definisjon*: «den delen av foreldrepengeperioden som er forbeholdt mor» (bokmål)
* *identifikator*: \https://data.nav.no/begrep/BEGREP-975
* *kontaktpunkt*: mailto:begrepskatalogen@nav.no[begrepskatalogen@nav.no]
* *publisert av*: NAV
|===

|===
a|*Eksempel på noen anbefalte opplysninger*, hentet fra Termlex til Standard Norge, 2024-09-16, for begrepet https://termlex.no/term/171137531106903/nb[«innholdsdefinisjon» &#x29C9;, window="_blank", role="ext-link"]:

* *fagområde*: «terminologi» (bokmål)
* *merknad*: «Innholdsdefinisjoner foretrekkes framfor andre typer definisjoner (3.3.1) fordi de tydelig avdekker kjennetegnene (3.2.1) til et begrep (3.2.7) i et begrepssystem (3.2.28): de bør brukes når det er mulig.» (bokmål)
* *tillatt term*: «intensjonell definisjon» (bokmål)
|===

|===
a|*Eksempel på noen valgfrie opplysninger*, ved å bruke et fiktivt eksempel, begrepet «fiktivt begrep»:

* *datastrukturterm*: aFictiveConcept
* *eksempel*: «eksempelbegrep, testbegrep» (bokmål)
* *frarådd term*: «fiktivt konsept» (bokmål)
* *status*: gyldig
* *verdiområde*: lovlige verdier: eksempelbegrep, testbegrep, tullebegrep
* *versjonsnummer*: 1.1
* *versjonsnote*: «Nå med 'tullebegrep' også som en lovlig verdi» (bokmål)
* *inngår i begrepssamling*: Fiktiv begrepssamling
|===

|===
a|*Eksempel på en generisk relasjon*, basert på https://data.norge.no/specification/termlosen/#kap1.4.1[figur 4 i kap. 1.4.1 i Termlosen &#x29C9;, window="_blank", role="ext-link"], for begrepet «tre»:

* *generaliserer*: «eviggrønt tre» (nynorsk)
* *inndelingskriterium*: «bladfelling» (nynorsk)
|===

|===
a|*Eksempel på en partitiv relasjon*, basert på https://data.norge.no/specification/termlosen/#kap1.4.2[figur 6 i kap. 1.4.2 i Termlosen &#x29C9;, window="_blank", role="ext-link"], for begrepet «rot»:

* *helhetsbegrep*: «tre» (nynorsk)
* *inndelingskriterium*: «anatomi» (nynorsk)
|===

|===
a|*Eksempel på en assosiativ relasjon*, hentet fra Felles datakatalog, 2022-11-25, for begrepet https://data.norge.no/concepts/adb06f11-2712-3e18-98ce-6def045418fb[«lovlig opphold» &#x29C9;, window="_blank", role="ext-link"]:

* *relasjonsrolle*: muliggjør
* *til-begrep*: https://data.norge.no/concepts/68950551-3fec-3fb4-a802-8127bac322c2[«medlem i folketrygden» &#x29C9;, window="_blank", role="ext-link"] 
|===
