=== Eksempler på begrepsbeskrivelser [[Del1-eksempler-på-begrepsbeskrivelser]]

|===
a|*Eksempel på en begrepsbeskrivelse med kun obligatoriske opplysninger*, hentet fra Felles datakatalog 2022-11-25, for begrepet https://data.norge.no/concepts/6bd8baed-c9d7-4dbc-b850-78ceeebdc1d5[«mødrekvote»]:

* *anbefalt term*: «mødrekvote» (bokmål), «mødrekvote» (nynorsk)
* *definisjon*: «den delen av foreldrepengeperioden som er forbeholdt mor» (bokmål)
* *identifikator*: https://data.norge.no/concepts/6bd8baed-c9d7-4dbc-b850-78ceeebdc1d5
* *kontaktpunkt*: mailto:begrepskatalogen@nav.no[begrepskatalogen@nav.no]
* *publisert av*: NAV
|===

|===
a|*Eksempel på noen anbefalte opplysninger*, hentet fra Termbasen til Standard Norge 2022-08-30, for begrepet https://termbasen.standard.no/term/165575613303956/nob[«innholdsdefinisjon»]:

* *fagområde*: «terminologi» (bokmål)
* *merknad*: «Innholdsdefinisjoner foretrekkes framfor andre typer definisjoner (3.3.1) fordi de tydelig avdekker kjennetegnene (3.2.1) til et begrep (3.2.7) i et begrepssystem (3.2.28): de bør brukes når det er mulig.» (bokmål)
* *tillatt term*: «intensjonell definisjon» (bokmål)
|===

|===
a|*Eksempel på noen valgfrie opplysninger*, ved å bruke et fiktivt eksempel, begrepet «fiktivt begrep»:

* *datastrukturterm*: aFictiveConcept
* *eksempel*: «eksempelbegrep, testbegrep» (bokmål)
* *frarådd term*: «fiktivt konsept» (bokmål)
* *status*: gyldig
* *verdiområde*: lovlige verdier: eksempelbegrep, testbegrep, tullebegrep
* *versjonsnummer*: 1.1
* *versjonsnote*: «Nå med 'tullebegrep' også som en lovlig verdi» (bokmål)
* *inngår i begrepssamling*: Fiktiv begrepssamling
|===

|===
a|*Eksempel på en generisk relasjon*, basert på https://data.norge.no/specification/termlosen/#kap1.4.1[figur 4 i Termlosen], for begrepet «tre»:

* *generaliserer*: «eviggrønt tre» (nynorsk)
* *inndelingskriterium*: «bladfelling» (nynorsk)
|===

|===
a|*Eksempel på en partitiv relasjon*, basert på https://data.norge.no/specification/termlosen/#kap1.4.2[figur 6 i Termlosen], for begrepet «rot»:

* *helhetsbegrep*: «tre» (nynorsk)
* *inndelingskriterium*: «anatomi» (nynorsk)
|===

|===
a|*Eksempel på en assosiativ relasjon*, hentet fra Felles datakatalog 2022-11-25, for begrepet https://data.norge.no/concepts/adb06f11-2712-3e18-98ce-6def045418fb[«lovlig opphold»]:

* *relasjonsrolle*: muliggjør
* *til-begrep*: https://data.norge.no/concepts/68950551-3fec-3fb4-a802-8127bac322c2[«medlem i folketrygden»] 
|===
