=== Krav til RDF-representasjon av Partitiv begrepsrelasjon [[Partitiv-begrepsrelasjon]]


[cols="30s,70d"]
|===
|_English name_ | _Partitive concept relation_
|Anvendelse / _Usage note_ | Klassen brukes til å representere en https://termbasen.standard.no/term/165575812309370/nob[partitiv begrepsrelasjon].

_This class is used to represent a https://termbasen.standard.no/term/165575812309370/eng[partitive concept relation]._
|URI |skosno:PartitiveConceptRelation
|Kravnivå / _Requirement level_ |Valgfri / _Optional_
|===

==== Obligatoriske egenskaper for _Partitiv begrepsrelasjon_ [[Partitiv-begrepsrelasjon-obligatoriske-egenskaper]]

===== Partitiv begrepsrelasjon – har delbegrep (skosno:hasPartitiveConcept) [[Partitiv-begrepsrelasjon-har-delbegrep]]

[cols="30s,70d"]
|===
|_English name_ | _has partitive concept_
|URI |skosno:hasPartitiveConcept
|Verdiområde / _Range_ |skos:Concept
|Anvendelse / _Usage note_ | Egenskapen brukes til å referere til et annet begrep (https://termbasen.standard.no/term/165575551206237/nob[delbegrepet]) som inngår i dette begrepet, i en partitiv begrepsrelasjon mellom disse.

_This property is used to refer to another concept (the https://termbasen.standard.no/term/165575551206237/eng[partitive concept]) that is part of this concept, in a partitive concept relation between the two concepts._
|Multiplisitet / _Multiplicity_ |1..n
|Kravnivå / _Requirement level_ |Obligatorisk / _Mandatory_
|Merknad / _Note_ | Enten denne eller egenskapen <<Partitiv-begrepsrelasjon-har-helhetsbegrep>> skal brukes, ikke begge samtidig.

_Either this property or the property <<Partitiv-begrepsrelasjon-har-helhetsbegrep>> shall be used, not both at the same time._
|===

Eksempel i RDF Turtle, for NAVs begrep 974 «foreldrepengeperiode»:
-----
<https://data.norge.no/concepts/4729eca4-f145-4518-8309-3e02a84dfc55> a skos:Concept ; # begrep «foreldrepengeperiode»
   skosno:hasPartitiveConceptRelation [ a skosno:PartitiveConceptRelation ; # har en partitiv relasjon
      skosno:hasPartitiveConcept <https://data.norge.no/concepts/6bd8baed-c9d7-4dbc-b850-78ceeebdc1d5> ; ] ; # .. som har delbegrep «mødrekvote»
  .
-----

===== Partitiv begrepsrelasjon – har helhetsbegrep (skosno:hasComprehensiveConcept) [[Partitiv-begrepsrelasjon-har-helhetsbegrep]]

[cols=«30s,70d«]
|===
|_English name_ | _has comprehensive concept_
|URI |skosno:hasComprehensiveConcept
|Verdiområde / _Range_ |skos:Concept
|Anvendelse / _Usage note_ | Egenskapen brukes til å referere til et annet begrep (https://termbasen.standard.no/term/165575551106220/nob[helhetsbegrepet]) som inneholder dette begrepet, i en partitiv begrepsrelasjon mellom disse.

_This property is used to refer to another concept (the https://termbasen.standard.no/term/165575551106220/eng[comprehensive concept]) that contains this concept, in a partitive concept relation between the two concepts._
|Multiplisitet / _Multiplicity_ |1..n
|Kravnivå / _Requirement level_ |Obligatorisk / _Mandatory_
|Merknad / _Note_ | Enten denne eller egenskapen <<Partitiv-begrepsrelasjon-har-delbegrep>> skal brukes, ikke begge samtidig.

_Either this property of the property <<Partitiv-begrepsrelasjon-har-delbegrep>> shall be used, not both at the same time._
|===

Eksempel i RDF Turtle, for NAVs begrep 975 «mødrekvote»:
-----
<https://data.norge.no/concepts/6bd8baed-c9d7-4dbc-b850-78ceeebdc1d5> a skos:Concept ; # begrep «mødrekvote»
   skosno:hasPartitiveConceptRelation [ a skosno:PartitiveConceptRelation ; # har en partitiv relasjon
      skosno:hasComprehensiveConcept <https://data.norge.no/concepts/4729eca4-f145-4518-8309-3e02a84dfc55> ; ] ; # … som har helhetsbegrep «foreldrepengeperiode»
  .
-----

==== Anbefalte egenskaper for _Partitiv begrepsrelasjon_ [[Partitiv-begrepsrelasjon-anbefalte-egenskaper]]


===== Partitiv begrepsrelasjon – inndelingskriterium (dct:description) [[Partitiv-begrepsrelasjon-inndelingskriterium]]

[cols="30s,70d"]
|===
|_English name_ | _criterion of subdivision_
|URI |dct:description
|Verdiområde / _Range_ |rdf:langString
|Anvendelse / _Usage note_ | Egenskapen brukes til å oppgi https://termbasen.standard.no/term/165577770503947/nob[inndelingskriterium] for begrepsrelasjonen. Egenskapen bør gjentas når teksten er på flere språk.

_This property is used to specify the https://termbasen.standard.no/term/165577770503947/eng[criterion of subdivision] for the concept relation. This property should be repeated for parallel language versions of the text._
|Multiplisitet / _Multiplicity_ |0..n
|Kravnivå / _Requirement level_ |Anbefalt / _Recommended_
|===

Eksempel i RDF Turtle:
-----
<tre> a skos:Concept ; # begrep ‘tre’
   skosno:hasPartitiveConceptRelation [ a skosno:PartitiveConceptRelation ; # har partitiv relasjon
      <skosno:hasPartitiveConcept> <stamme>, <rot>, <grein> # … som har delbegrep
      dct:description "anatomi"@nb ; ] ; # med inndelingskriterium «anatomi» (bokmål)
  .
-----
