=== Krav til RDF-representasjon av Definisjon [[Definisjon]]

[cols="30s,70d"]
|===
| _English name_ | _Definition_
| Anvendelse / _Usage note_ | Klassen brukes til å representere en https://termbasen.standard.no/term/165575612703717/nob[definisjon], når det er behov for å beskrive noe mer enn selve definisjonsteksten.

_This class is used to represent a https://termbasen.standard.no/term/165575612703717/eng[definition] when there is need to describe more than the definition itself._
| URI |euvoc:XlNote
| Kravnivå / _Requirement level_ |Anbefalt / _Recommended_
|===

==== Obligatoriske egenskaper for _Definisjon_ [[Definisjon-obligatoriske-egenskaper]]

===== Definisjon – tekst (rdf:value) [[Definisjon-tekst]]

[cols="30s,70d"]
|===
| _English name_ | _text_
| URI |rdf:value
| Verdiområde / _Range_  |rdf:langString
| Anvendelse / _Usage note_ | Egenskapen brukes til å oppgi definisjonsteksten i et gitt skriftspråk.

_This property is used to specify the definition text in a given language._
| Multiplisitet / _Multiplicity_  |1..1
| Kravnivå / _Requirement level_ |Obligatorisk / _Mandatory_
|===

Eksempel i RDF Turtle, for NAVs begrep 975 «mødrekvote»:
-----
<https://data.norge.no/concepts/6bd8baed-c9d7-4dbc-b850-78ceeebdc1d5> a skos:Concept ; # begrep «mødrekvote»
   euvoc:xlDefinition [ a euvoc:XlNote ; # definisjon
      rdf:value "den delen av foreldrepengeperioden som er forbeholdt mor"@nb ; ] ; # tekst på bokmål
     .
-----

==== Anbefalte egenskaper for _Definisjon_ [[Definisjon-anbefalte-egenskaper]]

===== Definisjon – forhold til kilde (skosno:relationshipWithSource) [[Definisjon-forhold-til-kilde]]

[cols="30s,70d"]
|===
| _English name_ | _relationship with source_
| URI |skosno:relationshipWithSource
| Verdiområde / _Range_  |skos:Concept
| Anvendelse / _Usage note_ | Egenskapen brukes til å oppgi forhold til kilde, som kodet verdi valgt fra et kontrollert vokabular.

_This property is used to specify the relationship between the definition and the source, as coded value chosen from a controlled vocabulary._
| Multiplisitet / _Multiplicity_  |0..1
| Kravnivå / _Requirement level_ |Anbefalt / _Recommended_
| Merknad / _Note_ | 
Når begrepsbeskrivelsen gjøres tilgjengelig utenfor virksomheten, og hvis en av kategoriene i det kontrollerte vokabularet https://data.norge.no/vocabulary/relationship-with-source-type[Typer forhold til kilde] passer til begrepets forhold til kilde, skal egenskapen referere til den aktuelle kategorien.

_When making the concept description available outside the organization, and if one of the categories in the controlled vocabulary https://data.norge.no/vocabulary/relationship-with-source-type[Types of relationship with source] is suitable for the concept's relationship with source, this property shall refer to that category._
|===

Eksempel i RDF Turtle, for NAVs begrep 975 «mødrekvote»:
-----
<https://data.norge.no/concepts/6bd8baed-c9d7-4dbc-b850-78ceeebdc1d5> a skos:Concept ; # begrep «mødrekvote»
  euvoc:xlDefinition [ a euvoc:XlNote ; # definisjon
      rdf:value "den delen av foreldrepengeperioden som er forbeholdt mor"@nb ; # tekst på bokmål
      skosno:relationshipWithSource <https://data.norge.no/vocabulary/relationship-with-source-type#derived-from-source> ; ] ; # forhold til kilde ‘basert på kilde’
  .
-----

===== Definisjon – kilde (dct:source) [[Definisjon-kilde]]

[cols="30s,70d"]
|===
| _English name_ | _source_
| URI |dct:source
| Verdiområde / _Range_  |rdfs:Resource or rdf:List
| Anvendelse / _Usage note_ | Egenskapen brukes til å referere til kilde.

_This property is used to refer to a source._
| Multiplisitet / _Multiplicity_  |0..n
| Kravnivå / _Requirement level_ |Anbefalt / _Recommended_
| Merknad / _Note_ | Bruk `rdf:List` når den ønskede rekkefølgen mellom kildene skal oppgis.

_Use `rdf:List` when the preferred order between the sources need to be specified._
|===

Eksempel i RDF Turtle, for NAVs begrep 975 «mødrekvote»:
-----
<https://data.norge.no/concepts/6bd8baed-c9d7-4dbc-b850-78ceeebdc1d5> a skos:Concept ; # begrep «mødrekvote»
   euvoc:xlDefinition [ a euvoc:XlNote ; # definisjon
      dct:source <https://lovdata.no/dokument/NL/lov/1997-02-28-19/kap14#kap14> ; ] ; # kilde
     .
-----

Et fiktivt eksempel i RDF Turtle, der det er behov for å oppgi rekkefølge mellom to referanser:
-----
<aFictiveConcept> a skos:Concept ; # et fiktivt begrep
   euvoc:xlDefinition [ a euvoc:XlNote ; # definisjon
      dct:source [ a rdf:List ; # en liste av kilder
         rdf:first <https://example.org/ref1> ; # ref. nr. 1
         rdf:rest [ a rdf:List ;
            rdf:first <https://example.org/ref2> ; # ref. nr. 2
            rdf:rest rdf:nil ;
            ] ;
         ] ;
      ] ;
   .
-----

==== Valgfrie egenskaper for _Definisjon_ [[Definisjon-valgfrie-egenskaper]]

===== Definisjon – målgruppe (dct:audience) [[Definisjon-målgruppe]]

[cols="30s,70d"]
|===
| _English name_ | _audience_
| URI |dct:audience
| Verdiområde / _Range_  |skos:Concept
| Anvendelse / _Usage note_ | Egenskapen brukes til å oppgi målgruppen for definisjonen. Verdien velges fra et kontrollert vokabular.

_This property is used to specify the audience of the definition, as a coded value chosen from a controlled vocabulary._
| Multiplisitet / _Multiplicity_  |0..1
| Kravnivå / _Requirement level_ |Valgfri / _Optional_
| Merknad / _Note_ | 
Når begrepsbeskrivelsen gjøres tilgjengelig utenfor virksomheten, og hvis en av kategoriene i det kontrollerte vokabularet https://data.norge.no/vocabulary/audience-type[Målgruppetype] passer til begrepets målgruppe, skal egenskapen referere til den aktuelle kategorien.

_When making the concept description available outside the organization, and if one of the categories in the controlled vocabulary https://data.norge.no/vocabulary/audience-type[Audience type] is suitable for the audience of the concept, this property shall refer to that category._
|===

Eksempel i RDF Turtle:
-----
<eksempel-begrep> a skos:Concept ; # eksempel-begrep
   euvoc:xlDefinition [ a euvoc:XlNote ; # definisjon
      dct:audience <https://data.norge.no/vocabulary/audience-type#public> ; ] ; # målgruppe
  .
-----
