=== Krav til RDF-representasjon av Generisk begrepsrelasjon [[Generisk-begrepsrelasjon]]

[cols="30s,70d"]
|===
| _English name_  | _Generic concept relation_
| Anvendelse / _Usage note_  | Klassen brukes til å representere en https://termlex.no/term/174124356208619/nb[generisk begrepsrelasjon &#x29C9;, window="_blank", role="ext-link"].

__This class is used to represent a https://termlex.no/term/174124356208619/en[generic concept relation &#x29C9;, window="_blank", role="ext-link"].__
| URI  |skosno:GenericConceptRelation
| Kravnivå / _Requirement level_  |Valgfri / _Optional_
|===

==== Obligatoriske egenskaper for Generisk begrepsrelasjon [[Generisk-begrepsrelasjon-obligatoriske-egenskaper]]

===== Generisk begrepsrelasjon – har overbegrep (skosno:hasGenericConcept) [[Generisk-begrepsrelasjon-har-overbegrep]]

[cols="30s,70d"]
|===
| _English name_  | _has generic concept_
| URI  |skosno:hasGenericConcept
| Verdiområde / _Range_  |skos:Concept
| Anvendelse / _Usage note_ | Egenskapen brukes til å referere til https://termlex.no/term/174124355808089/nb[det generiske begrepet &#x29C9;, window="_blank", role="ext-link"] i en generisk begrepsrelasjon.

__This property is used to specify the https://termlex.no/term/174124355808089/en[generic concept &#x29C9;, window="_blank", role="ext-link"] in a generic concept relation.__
| Multiplisitet / _Multiplicity_  |1..n
| Kravnivå / _Requirement level_  |Obligatorisk / _Mandatory_
| Merknad 1 / _Note 1_ | Enten denne eller egenskapen <<Generisk-begrepsrelasjon-har-underbegrep>> skal brukes, men ikke begge samtidig.

_Either this property or the property <<Generisk-begrepsrelasjon-har-underbegrep>> shall be used, not both at the same time._
| Merknad 2 | Vi har i denne standarden valgt å bruke de norske termene «overbegrep» og «underbegrep» kun i generiske relasjoner, mens NS-ISO 1087 bruker disse i både generiske og partitive relasjoner.
|===

Eksempel i RDF Turtle, for NAVs begrep 974 «foreldrepengeperiode»:
-----
<https://data.norge.no/concepts/4729eca4-f145-4518-8309-3e02a84dfc55> a skos:Concept ; # begrep «foreldrepengeperiode»
   skosno:hasGenericConceptRelation [ a skosno:GenericConceptRelation ; # har generisk relasjon
      skosno:hasGenericConcept <https://data.norge.no/concepts/680b83b6-46f5-30f2-96f7-e36c4e5cf3d1> ; ] ; # som har overbegrep «ytelsesperiode»
     .
-----

===== Generisk begrepsrelasjon – har underbegrep (skosno:hasSpecificConcept) [[Generisk-begrepsrelasjon-har-underbegrep]]

[cols="30s,70d"]
|===
| _English name_  | _has specific concept_
| URI  |skosno:hasSpecificConcept
| Verdiområde / _Range_  |skos:Concept
| Anvendelse / _Usage note_  | Egenskapen brukes til å referere til https://termlex.no/term/174124355707950/nb[det spesifikke begrepet &#x29C9;, window="_blank", role="ext-link"] i en generisk begrepsrelasjon.

__This property is used to refer to https://termlex.no/term/174124355707950/en[specific concept &#x29C9;, window="_blank", role="ext-link"] in a generic concept relation.__
| Multiplisitet / _Multiplicity_  |1..n
| Kravnivå / _Requirement level_  |Obligatorisk / _Mandatory_
| Merknad 1 / _Note 1_ | Enten denne eller egenskapen <<Generisk-begrepsrelasjon-har-overbegrep>> skal brukes, ikke begge samtidig.

_Either this property or the property <<Generisk-begrepsrelasjon-har-overbegrep>> shall be used, not both at the same time._
| Merknad 2 | Vi har i denne standarden valgt å bruke de norske termene «overbegrep» og «underbegrep» kun i generiske relasjoner, mens NS-ISO 1087 bruker disse i både generiske og partitive relasjoner.
|===

Eksempel i RDF Turtle, for NAVs begrep 625 «ytelsesperiode»:
-----
<https://data.norge.no/concepts/680b83b6-46f5-30f2-96f7-e36c4e5cf3d1> a skos:Concept ; # begrep «ytelsesperiode»
   skosno:hasGenericConceptRelation [ a skosno:GenericConceptRelation ; # har generisk relasjon
      skosno:hasSpecificConcept <https://data.norge.no/concepts/4729eca4-f145-4518-8309-3e02a84dfc55> ; ] ; # som har underbegrep «foreldrepengeperiode»
     .
-----

==== Anbefalte egenskaper for Generisk begrepsrelasjon [[Generisk-begrepsrelasjon-anbefalte-egenskaper]]


===== Generisk begrepsrelasjon – inndelingskriterium (dct:description) [[Generisk-begrepsrelasjon-inndelingskriterium]]

[cols="30s,70d"]
|===
| _English name_  | _criterion of subdivision_
| URI  |dct:description
| Verdiområde / _Range_  |rdf:langString
| Anvendelse / _Usage note_  | Egenskapen brukes til å oppgi https://termlex.no/term/171137526103099/nb[inndelingskriterium &#x29C9;, window="_blank", role="ext-link"] for begrepsrelasjonen. Egenskapen bør gjentas når teksten er på flere språk.

__This property is used to specify the https://termlex.no/term/171137526103099/en[criterion of subdivision &#x29C9;, window="_blank", role="ext-link"] for the concept relation. This property should be repeated for parallel language versions of the text.__
| Multiplisitet / _Multiplicity_  |0..n
| Kravnivå / _Requirement level_  |Anbefalt / _Recommended_
|===

Eksempel i RDF Turtle:
-----
<tre> a skos:Concept ; # begrep ‘tre’
   skosno:hasGenericConceptRelation [ a skosno:GenericConceptRelation ; # har generisk relasjon
      skosno:hasSpecificConcept <løvtre> ; # … som har ‘løvtre’ som underbegrep
      dct:description "anatomi"@nb ; ] ; # med inndelingskriterium «anatomi» (bokmål)
  .
-----
