== Vedlegg C – Om begrepsrelasjoner [[Om-begrepsrelasjoner]]


_Vedlegget er deskriptivt_.

Et begrep kan ha relasjoner til andre begreper. En relasjon består av to begreper pluss en betydning som kan uttrykkes med tekst eller type. https://data.norge.no/specification/termlosen/#kap1.4[Omgrepssystem i Termlosen &#x29C9;, window="_blank", role="ext-link"] nevner tre hovedgrupper av relasjoner: generiske, partitive og assosiative.

En __generisk__ relasjon består et overbegrep og et underbegrep. Underbegrepet har de samme kjennetegnene som overbegrepet, og minst ett atskillende kjennetegn i tillegg. Et eksempel fra https://data.norge.no/specification/termlosen#kap1.4.1[Termlosen &#x29C9;, window="_blank", role="ext-link"]: begrepet «tre» kan ha et underbegrep «eviggrønt tre» og et annet underbegrep «sommergrønt tre». Her har vi altså to relasjoner. Valget av atskillende kjennetegn kalles __inndelingskriterium__. I dette eksemplet er inndelingskriteriet «bladfelling».

Generiske relasjoner danner ofte rene hierarkier, men i noen tilfeller kan det være aktuelt å gi et underbegrep flere overbegreper.

En __partitiv__ relasjon angir at et begrep _er del av_ (inngår i) et annet begrep, som dermed __inneholder__ det første begrepet. Relasjonen skal kunne forstås begge veier, for eksempel:
[no-bullet]
*   «mødrekvote» __er del av__ «foreldrepengeperiode»
*   «foreldrepengeperiode» __inneholder__ «mødrekvote»

Begrepet «foreldrepengeperiode» __inneholder__ også begrepene «fedrekvote» og «fellesperiode», i tillegg til «mødrekvote». Dermed har vi til sammen tre partitive relasjoner med utgangspunkt i begrepet «foreldrepengeperiode».

Et begrep kan være del av flere andre begreper. For eksempel kan begrepet «styringsenhet» være del av begrepet «lydanlegg» og begrepet «lysanlegg». Til sammen har vi da to partitive relasjoner med utgangspunkt i begrepet «styringsenhet».

En __assosiativ__ relasjon kan være av en av mange forskjellige typer. Her blir rollene viktige, for de er ikke forutbestemte slik som i generiske og partitive relasjoner. For eksempel kan vi ønske å uttrykke at
[no-bullet]
* begrep A __muliggjør__ begrep B

Her er __muliggjør__ den rollen begrep A spiller overfor begrep B. Leser vi relasjonen motsatt vei, må vi i dette tilfellet velge en annen rolle: begrep B __forutsetter__ begrep A.

Det er opp til begrepsforfatterne å velge hvilke typer assosiative relasjoner de trenger. Relasjonene skal kunne forstås begge veier, og ordlyden hjelper oss til å bestemme typen. Eksempler på assosiative relasjoner kan være

* «forutsetter – muliggjør»
* «har nært samsvar med – har nært samsvar med»
* «erstatter – er erstattet av»

Merk at noen relasjonstyper er symmetriske; de leses likt begge veier. Dette gjelder blant andre relasjonstypene «har nært samsvar med» og «er relatert til». Det finnes ingen endelig liste over assosiative relasjonstyper, men https://online.standard.no/ns-iso-704-2022[NS-ISO 704:2022  __Terminology work - Principles and methods__ &#x29C9;, window="_blank", role="ext-link"] gir mange gode forslag.
