=== Om dette kapittelet [[Om-del2]]

Dette kapittelet spesifiserer hvordan begrepsbeskrivelsene i <<Del1>> skal uttrykkes på en form som er i henhold til https://www.w3.org/RDF/[_Resource Desciption Framework (RDF)_]. RDF gir struktur og syntaks. Innholdet skal uttrykkes i henhold til https://www.w3.org/TR/2009/REC-skos-reference-20090818/[_SKOS Simple Knowledge Organization System Reference_]. SKOS er et vokabular (en metamodell) for de mest sentrale klassene og egenskapene vi behøver når vi beskriver begreper. Det vi trenger i tillegg til SKOS, for å oppgi datoer, kontaktpunkter m.m., må vi hente fra andre vokabularer. <<Navnerom-brukt-i-standarden>> gir en oversikt over de vokabularene som er brukt. Denne standarden er dermed en norsk applikasjonsprofil av SKOS (SKOS-AP-NO-Begrep).

Se ellers https://fellesdatakatalog.digdir.no/specification/tbx-ap-no[TBX-AP-NO] for hvordan begrepsbeskrivelsene i <<Del1>> skal uttrykkes på en form som er i henhold til TBX-rammeverket spesifisert i https://standard.no/no/Nettbutikk/produktkatalogen/Produktpresentasjon/?ProductID=1035256[NS-ISO 30042:2019]. 
