== Om denne standarden [[Om-denne-standarden]]

=== Formål [[Formål]]

Det er et uttrykt ønske, både fra regjeringshold og fra offentlig sektor, at ulike deler av forvaltningen skal kunne gjenbruke hverandres informasjon i større grad. I https://www.regjeringen.no/no/dokumenter/en-digital-offentlig-sektor/id2653874/?ch=4[regjeringens digitaliseringsstrategi for offentlig sektor 2019–2025] leser vi:

[no-bullet]
** _Brukerne skal unngå å oppgi informasjon som det offentlige allerede har innhentet. Økt deling av data er også en forutsetning for utvikling av sammenhengende tjenester på tvers av sektorer og forvaltningsnivåer. Offentlig sektor skal dele data når den kan og skjerme data når den må. Åpne offentlige data skal gjøres tilgjengelig for viderebruk til utvikling av nye tjenester og verdiskaping i næringslivet._

Når offentlige organer legger ut data til deling og viderebruk, er det viktig at de forklarer nøye hva de tilbyr. De bør derfor knytte dataene til begreper, som må være definert slik at mottakere kan forstå hva slags opplysninger dette er, hva de betyr, og hva de kan (og ikke kan) brukes til. Begrepsarbeid er dermed en forutsetning for deling av data med andre virksomheter.


Standarden skal sikre at begreper som forvaltes av offentlig forvaltning, beskrives og tilgjengeliggjøres på en standardisert og maskinlesbar måte, slik at virksomheter enklere kan ta i bruk og bygge videre på begrepsarbeid som andre har gjort.

=== Omfang og avgrensinger [[Omfang-og-avgrensninger]]

Standarden spesifiserer

* i <<Del1>>, hva som skal/bør/kan tas med når et begrep eller en begrepssamling beskrives
* i <<Del2>>, hvordan beskrivelser av begreper og begrepssamlinger gjøres tilgjengelige i maskinlesbare formater i henhold til https://www.w3.org/TR/skos-reference/[_SKOS Simple Knowledge Organization System_]

Se ellers bruksområdet https://www.digdir.no/1483[Omgrepsanalyse og definisjonsarbeid] i _Referansekatalogen_ for andre aktuelle standarder og veiledere, bl.a. https://fellesdatakatalog.digdir.no/specification/tbx-ap-no[TBX-AP-NO] som spesifiserer hvordan beskrivelser av begreper og begrepssamlinger gjøres tilgjengelige i maskinlesbare formater i henhold til TBX-rammeverket spesifisert i https://standard.no/no/Nettbutikk/produktkatalogen/Produktpresentasjon/?ProductID=1035256[NS-ISO 30042:2019].

=== Målgrupper [[Målgrupper]]

Standarden er primært for

* deg som beskriver og tilgjengeliggjør din virksomhets begreper og begrepssamlinger
* deg som utvikler/tilpasser verktøystøtte for å beskrive begreper og/eller for å tilgjengeliggjøre begrepsbeskrivelser

Du kan også ha nytte av å lese standarden hvis hensikten er å forstå andres begrepsbeskrivelser.

=== Forvaltningsregime [[Forvaltningsregime]]

Standarden forvaltes av https://digdir.no/[Digitaliseringsdirektoratet (Digdir)].

Digdir håndterer mindre endringer. Ved behov for større endringer vil Digdir sette sammen en arbeidsgruppe med representanter fra aktuelle virksomheter. Arbeidsgruppen utarbeider forslag til den reviderte versjonen som sendes ut på åpen høring før fastsetting.

=== Kravnivåene i denne standarden [[Kravnivåene-i-denne-standarden]]


Standarden bruker ordene «obligatorisk», «anbefalt» og «valgfri». Disse er forklart i https://data.norge.no/specification/dcat-ap-no/#Om-kravene[DCAT-AP-NO], og forklaringene gjentas ikke her.

=== Hvordan du leser denne standarden [[Hvordan-du-leser-denne-standarden]]


<<Del1>> er ment for alle, uavhengig av teknisk bakgrunn. Kravene er formulert uavhengig av hvordan de implementeres.

<<Del2>> er ment for lesere som skal utvikle/tilpasse verktøystøtte for begrepsbeskrivelser. Den spesifiserer hvordan kravene beskrevet i del 1 skal implementeres iht. https://www.w3.org/RDF/[_Resource Description Framework (RDF)_] og https://www.w3.org/TR/skos-reference/[_SKOS Simple Knowledge Organization System_].

Eksemplene i denne standarden er deskriptive. De kan inneholde fiktive data. Ikke alle eksemplene er komplette, dvs. at de kan mangle obligatoriske opplysninger.
