=== Om del 2 [[Om-del2]]


Denne delen av standarden spesifiserer hvordan vi skal beskrive begreper og begrepssamlinger på en maskinlesbar måte, slik at virksomheter kan tilgjengeliggjøre begrepene sine på en standardisert og maskinlesbar måte.

Del 2 spesifiserer hvordan begrepsbeskrivelsene i <<Del1, del 1>> skal uttrykkes på en form som er i henhold til https://www.w3.org/RDF/[_Resource Desciption Framework (RDF)_]. RDF gir struktur og syntaks. Innholdet skal uttrykkes i henhold til https://www.w3.org/TR/2009/REC-skos-reference-20090818/[_SKOS Simple Knowledge Organization System Reference_]. SKOS er et vokabular (en metamodell) for de mest sentrale klassene og egenskapene vi behøver når vi beskriver begreper. Det vi trenger i tillegg til SKOS, for å oppgi datoer, kontaktpunkter m.m., må vi hente fra andre vokabularer. <<Navnerom-brukt-i-standarden>> gir en oversikt over de vokabularene som er brukt. Denne standarden er dermed en norsk applikasjonsprofil av SKOS (SKOS-AP-NO-Begrep).
