name: Build adocs and publish v1 to production

permissions:
  contents: read

on:
  push:
    branches:
      - v1
    paths:
      - docs/**
  workflow_dispatch:

jobs:
  upload-files-to-production:
    name: Upload specification to static-rdf-server
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-upload-files.yaml@main
    with:
      ref: v1
      program_html: |
        asciidoctor -D docs -o index.html -a lang=nb docs/main.adoc
      program_pdf: |
        asciidoctor-pdf -D docs -o files/skos-ap-no-begrep-v1xx.pdf -a lang=nb docs/main.adoc
      program_pdf_continue_on_error: true
      host: https://fellesdatakatalog.digdir.no
      ontology: skos-ap-no-begrep
      ontology-type: specification
      version: v1.1
      files: |
        docs/index.html text/html nb
        docs/files/skos-ap-no-begrep-v1xx.pdf application/pdf nb files/skos-ap-no-begrep-v1xx.pdf
        docs/images/digitaliseringsdirektoratet.png image/png nb images/digitaliseringsdirektoratet.png
    secrets:
      STATIC_RDF_SERVER_API_KEY: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}