name: Build adocs and publish v2 to production

permissions:
  contents: read

on:
  push:
    branches:
      - v2
    paths:
      - docs/**
  workflow_dispatch:

jobs:
  upload-files-to-production:
    name: Upload specification to static-rdf-server
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-upload-files.yaml@main
    with:
      ref: v2
      program_html: |
        asciidoctor -D docs -o index.html -a lang=nb docs/main.adoc
      program_pdf: |
        asciidoctor-pdf -D docs -o files/skos-ap-no-begrep.pdf -a lang=nb docs/main.adoc
      program_pdf_continue_on_error: true
      host: https://data.norge.no
      ontology: skos-ap-no-begrep
      ontology-type: specification
      files: |
        docs/index.html text/html nb
        docs/files/skos-ap-no-begrep.pdf application/pdf nb files/skos-ap-no-begrep.pdf
        docs/images/Digdir.png image/png nb images/Digdir.png
        docs/images/RDF-eksempel-assosiativrelasjon.png image/png nb images/RDF-eksempel-assosiativrelasjon.png
        docs/images/RDF-eksempel-definisjon-1.png image/png nb images/RDF-eksempel-definisjon-1.png
        docs/images/RDF-eksempel-definisjon-2.png image/png nb images/RDF-eksempel-definisjon-2.png
        docs/images/RDF-eksempel-partitivrelasjon.png image/png nb images/RDF-eksempel-partitivrelasjon.png
        docs/images/SKOS-AP-NO-Begrep-kun-med-begrepsrelasjoner.png image/png nb images/SKOS-AP-NO-Begrep-kun-med-begrepsrelasjoner.png
        docs/images/SKOS-AP-NO-Begrep-kun-obligatoriske.png image/png nb images/SKOS-AP-NO-Begrep-kun-obligatoriske.png
        docs/images/SKOS-AP-NO-Begrep-uten-relasjoner.png image/png nb images/SKOS-AP-NO-Begrep-uten-relasjoner.png
    secrets:
      STATIC_RDF_SERVER_API_KEY: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}