name: Build adocs and publish develop to GitHub pages

permissions:
  contents: write

on:
  push:
    branches:
      - develop
    paths:
      - docs/**
  workflow_dispatch:

jobs:
  build-adocs:
    name: asciidoctor build
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-github-pages.yaml@main
    with:
      ref: develop
      program_html: |
        asciidoctor -D docs -o index.html -a lang=nb docs/main.adoc
      program_pdf: |
        asciidoctor-pdf -D docs -o files/skos-ap-no-begrep.pdf -a lang=nb docs/main.adoc
      program_pdf_continue_on_error: true
      publish_branch: gh-pages
      publish_dir: ./docs
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}