name: Publish ontology to data.norge.no/vocabulary

permissions:
  contents: read

on:
  push:
    branches:
      - v2
    paths:
      - ontology/**
  workflow_dispatch:

jobs:
  upload-files-to-production:
    name: Upload vocabulary to static-rdf-server
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-upload-files.yaml@main
    with:
      ref: v2
      program_html: |
        asciidoctor -a data-uri -D ontology -o index-en.html -a lang=en ontology/main-en.adoc
        asciidoctor -a data-uri -D ontology -o index-nb.html -a lang=nb ontology/main-nb.adoc
      host: https://data.norge.no
      ontology: skosno
      ontology-type: vocabulary
      files: |
        ontology/skosno.ttl text/turtle en
        ontology/index-en.html text/html en
        ontology/index-nb.html text/html nb
    secrets:
      STATIC_RDF_SERVER_API_KEY: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}