name: Publish ontology to data.norge.no/vocabulary

on:
  push:
    branches:
      - v2
    paths:
      - ontology/**
  workflow_dispatch:

jobs:
  adoc_build_and_upload:
    name: Adoc-build html and Upload vocabulary to static-rdf-server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: v2

      - name: Build html
        id: adocbuild_html
        uses: tonynv/asciidoctor-action@master
        with:
          program: "asciidoctor -D ontology -o index.html -a lang=nb ontology/main.adoc"

      - name: Upload files to static-rdf-server
        uses: Informasjonsforvaltning/upload-files-to-static-rdf-server-action@v3.2.0
        id: upload-files
        with:
          ontology-type: "vocabulary"
          ontology: "skosno"
          host: "https://data.norge.no"
          api-key: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}
          files: |
            ontology/skosno.ttl text/turtle en
            ontology/index.html text/html nb
