name: Publish ontology to data.norge.no/vocabulary

permissions:
  contents: read

on:
  push:
    branches:
      - v2
    paths:
      - ontology/**
  workflow_dispatch:

jobs:
  adoc_build_and_upload:
    name: Adoc-build html and Upload vocabulary to static-rdf-server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          ref: v2
          submodules: true
          fetch-depth: 0

      - name: Update submodules to latest main
        run: |
          git submodule foreach --recursive git fetch origin
          git submodule foreach --recursive git checkout origin/main

      - name: Build html nb
        id: adocbuild_html_nb
        uses: Analog-inc/asciidoctor-action@master
        with:
          shellcommand: "asciidoctor -a data-uri -D ontology -o index-nb.html -a lang=nb ontology/main-nb.adoc"

      - name: Build html en
        id: adocbuild_html_en
        uses: Analog-inc/asciidoctor-action@master
        with:
          shellcommand: "asciidoctor -a data-uri -D ontology -o index-en.html -a lang=en ontology/main-en.adoc"

      - name: Upload files to static-rdf-server
        uses: Informasjonsforvaltning/upload-files-to-static-rdf-server-action@84beeeacd364f310ef6a253bc079354cdf62e5dd
        id: upload-files
        with:
          ontology-type: "vocabulary"
          ontology: "skosno"
          host: "https://data.norge.no"
          api-key: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}
          files: |
            ontology/skosno.ttl text/turtle en
            ontology/index-en.html text/html en
            ontology/index-nb.html text/html nb
