name: build html skosno-v1

on:
  push:
    branches:
    - v1
    paths:
    - ontology/**

jobs:
  build_html:
    runs-on: ubuntu-18.04
    name: html build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: make build directory
      run: |
        mkdir ontology/build

    - name: copy index.html
      uses: canastro/copy-file-action@master
      with:
        source: "ontology/index.html"
        target: "ontology/build/index.html"

    - name: copy skosno-v1.ttl
      uses: canastro/copy-file-action@master
      with:
        source: "ontology/skosno-v1.ttl"
        target: "ontology/build/skosno-v1.ttl"

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: skosno-v1_vocabulary
        publish_dir: ontology/build
